// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package datastorecluster

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.datastoreCluster.DatastoreCluster",
		reflect.TypeOf((*DatastoreCluster)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributes", GoGetter: "CustomAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributesInput", GoGetter: "CustomAttributesInput"},
			_jsii_.MemberProperty{JsiiProperty: "datacenterId", GoGetter: "DatacenterId"},
			_jsii_.MemberProperty{JsiiProperty: "datacenterIdInput", GoGetter: "DatacenterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "folder", GoGetter: "Folder"},
			_jsii_.MemberProperty{JsiiProperty: "folderInput", GoGetter: "FolderInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomAttributes", GoMethod: "ResetCustomAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "resetFolder", GoMethod: "ResetFolder"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsAdvancedOptions", GoMethod: "ResetSdrsAdvancedOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsAutomationLevel", GoMethod: "ResetSdrsAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsDefaultIntraVmAffinity", GoMethod: "ResetSdrsDefaultIntraVmAffinity"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsEnabled", GoMethod: "ResetSdrsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsFreeSpaceThreshold", GoMethod: "ResetSdrsFreeSpaceThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsFreeSpaceThresholdMode", GoMethod: "ResetSdrsFreeSpaceThresholdMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsFreeSpaceUtilizationDifference", GoMethod: "ResetSdrsFreeSpaceUtilizationDifference"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsIoBalanceAutomationLevel", GoMethod: "ResetSdrsIoBalanceAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsIoLatencyThreshold", GoMethod: "ResetSdrsIoLatencyThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsIoLoadBalanceEnabled", GoMethod: "ResetSdrsIoLoadBalanceEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsIoLoadImbalanceThreshold", GoMethod: "ResetSdrsIoLoadImbalanceThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsIoReservableIopsThreshold", GoMethod: "ResetSdrsIoReservableIopsThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsIoReservablePercentThreshold", GoMethod: "ResetSdrsIoReservablePercentThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsIoReservableThresholdMode", GoMethod: "ResetSdrsIoReservableThresholdMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsLoadBalanceInterval", GoMethod: "ResetSdrsLoadBalanceInterval"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsPolicyEnforcementAutomationLevel", GoMethod: "ResetSdrsPolicyEnforcementAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsRuleEnforcementAutomationLevel", GoMethod: "ResetSdrsRuleEnforcementAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsSpaceBalanceAutomationLevel", GoMethod: "ResetSdrsSpaceBalanceAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsSpaceUtilizationThreshold", GoMethod: "ResetSdrsSpaceUtilizationThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetSdrsVmEvacuationAutomationLevel", GoMethod: "ResetSdrsVmEvacuationAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsAdvancedOptions", GoGetter: "SdrsAdvancedOptions"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsAdvancedOptionsInput", GoGetter: "SdrsAdvancedOptionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsAutomationLevel", GoGetter: "SdrsAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsAutomationLevelInput", GoGetter: "SdrsAutomationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsDefaultIntraVmAffinity", GoGetter: "SdrsDefaultIntraVmAffinity"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsDefaultIntraVmAffinityInput", GoGetter: "SdrsDefaultIntraVmAffinityInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsEnabled", GoGetter: "SdrsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsEnabledInput", GoGetter: "SdrsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsFreeSpaceThreshold", GoGetter: "SdrsFreeSpaceThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsFreeSpaceThresholdInput", GoGetter: "SdrsFreeSpaceThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsFreeSpaceThresholdMode", GoGetter: "SdrsFreeSpaceThresholdMode"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsFreeSpaceThresholdModeInput", GoGetter: "SdrsFreeSpaceThresholdModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsFreeSpaceUtilizationDifference", GoGetter: "SdrsFreeSpaceUtilizationDifference"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsFreeSpaceUtilizationDifferenceInput", GoGetter: "SdrsFreeSpaceUtilizationDifferenceInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoBalanceAutomationLevel", GoGetter: "SdrsIoBalanceAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoBalanceAutomationLevelInput", GoGetter: "SdrsIoBalanceAutomationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoLatencyThreshold", GoGetter: "SdrsIoLatencyThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoLatencyThresholdInput", GoGetter: "SdrsIoLatencyThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoLoadBalanceEnabled", GoGetter: "SdrsIoLoadBalanceEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoLoadBalanceEnabledInput", GoGetter: "SdrsIoLoadBalanceEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoLoadImbalanceThreshold", GoGetter: "SdrsIoLoadImbalanceThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoLoadImbalanceThresholdInput", GoGetter: "SdrsIoLoadImbalanceThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoReservableIopsThreshold", GoGetter: "SdrsIoReservableIopsThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoReservableIopsThresholdInput", GoGetter: "SdrsIoReservableIopsThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoReservablePercentThreshold", GoGetter: "SdrsIoReservablePercentThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoReservablePercentThresholdInput", GoGetter: "SdrsIoReservablePercentThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoReservableThresholdMode", GoGetter: "SdrsIoReservableThresholdMode"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsIoReservableThresholdModeInput", GoGetter: "SdrsIoReservableThresholdModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsLoadBalanceInterval", GoGetter: "SdrsLoadBalanceInterval"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsLoadBalanceIntervalInput", GoGetter: "SdrsLoadBalanceIntervalInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsPolicyEnforcementAutomationLevel", GoGetter: "SdrsPolicyEnforcementAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsPolicyEnforcementAutomationLevelInput", GoGetter: "SdrsPolicyEnforcementAutomationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsRuleEnforcementAutomationLevel", GoGetter: "SdrsRuleEnforcementAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsRuleEnforcementAutomationLevelInput", GoGetter: "SdrsRuleEnforcementAutomationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsSpaceBalanceAutomationLevel", GoGetter: "SdrsSpaceBalanceAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsSpaceBalanceAutomationLevelInput", GoGetter: "SdrsSpaceBalanceAutomationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsSpaceUtilizationThreshold", GoGetter: "SdrsSpaceUtilizationThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsSpaceUtilizationThresholdInput", GoGetter: "SdrsSpaceUtilizationThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsVmEvacuationAutomationLevel", GoGetter: "SdrsVmEvacuationAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "sdrsVmEvacuationAutomationLevelInput", GoGetter: "SdrsVmEvacuationAutomationLevelInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_DatastoreCluster{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.datastoreCluster.DatastoreClusterConfig",
		reflect.TypeOf((*DatastoreClusterConfig)(nil)).Elem(),
	)
}
