// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package computecluster

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.computeCluster.ComputeCluster",
		reflect.TypeOf((*ComputeCluster)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributes", GoGetter: "CustomAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributesInput", GoGetter: "CustomAttributesInput"},
			_jsii_.MemberProperty{JsiiProperty: "datacenterId", GoGetter: "DatacenterId"},
			_jsii_.MemberProperty{JsiiProperty: "datacenterIdInput", GoGetter: "DatacenterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "dpmAutomationLevel", GoGetter: "DpmAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "dpmAutomationLevelInput", GoGetter: "DpmAutomationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "dpmEnabled", GoGetter: "DpmEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "dpmEnabledInput", GoGetter: "DpmEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "dpmThreshold", GoGetter: "DpmThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "dpmThresholdInput", GoGetter: "DpmThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "drsAdvancedOptions", GoGetter: "DrsAdvancedOptions"},
			_jsii_.MemberProperty{JsiiProperty: "drsAdvancedOptionsInput", GoGetter: "DrsAdvancedOptionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "drsAutomationLevel", GoGetter: "DrsAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "drsAutomationLevelInput", GoGetter: "DrsAutomationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "drsEnabled", GoGetter: "DrsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "drsEnabledInput", GoGetter: "DrsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "drsEnablePredictiveDrs", GoGetter: "DrsEnablePredictiveDrs"},
			_jsii_.MemberProperty{JsiiProperty: "drsEnablePredictiveDrsInput", GoGetter: "DrsEnablePredictiveDrsInput"},
			_jsii_.MemberProperty{JsiiProperty: "drsEnableVmOverrides", GoGetter: "DrsEnableVmOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "drsEnableVmOverridesInput", GoGetter: "DrsEnableVmOverridesInput"},
			_jsii_.MemberProperty{JsiiProperty: "drsMigrationThreshold", GoGetter: "DrsMigrationThreshold"},
			_jsii_.MemberProperty{JsiiProperty: "drsMigrationThresholdInput", GoGetter: "DrsMigrationThresholdInput"},
			_jsii_.MemberProperty{JsiiProperty: "drsScaleDescendantsShares", GoGetter: "DrsScaleDescendantsShares"},
			_jsii_.MemberProperty{JsiiProperty: "drsScaleDescendantsSharesInput", GoGetter: "DrsScaleDescendantsSharesInput"},
			_jsii_.MemberProperty{JsiiProperty: "folder", GoGetter: "Folder"},
			_jsii_.MemberProperty{JsiiProperty: "folderInput", GoGetter: "FolderInput"},
			_jsii_.MemberProperty{JsiiProperty: "forceEvacuateOnDestroy", GoGetter: "ForceEvacuateOnDestroy"},
			_jsii_.MemberProperty{JsiiProperty: "forceEvacuateOnDestroyInput", GoGetter: "ForceEvacuateOnDestroyInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlFailoverHostSystemIds", GoGetter: "HaAdmissionControlFailoverHostSystemIds"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlFailoverHostSystemIdsInput", GoGetter: "HaAdmissionControlFailoverHostSystemIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlHostFailureTolerance", GoGetter: "HaAdmissionControlHostFailureTolerance"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlHostFailureToleranceInput", GoGetter: "HaAdmissionControlHostFailureToleranceInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlPerformanceTolerance", GoGetter: "HaAdmissionControlPerformanceTolerance"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlPerformanceToleranceInput", GoGetter: "HaAdmissionControlPerformanceToleranceInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlPolicy", GoGetter: "HaAdmissionControlPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlPolicyInput", GoGetter: "HaAdmissionControlPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlResourcePercentageAutoCompute", GoGetter: "HaAdmissionControlResourcePercentageAutoCompute"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlResourcePercentageAutoComputeInput", GoGetter: "HaAdmissionControlResourcePercentageAutoComputeInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlResourcePercentageCpu", GoGetter: "HaAdmissionControlResourcePercentageCpu"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlResourcePercentageCpuInput", GoGetter: "HaAdmissionControlResourcePercentageCpuInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlResourcePercentageMemory", GoGetter: "HaAdmissionControlResourcePercentageMemory"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlResourcePercentageMemoryInput", GoGetter: "HaAdmissionControlResourcePercentageMemoryInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlSlotPolicyExplicitCpu", GoGetter: "HaAdmissionControlSlotPolicyExplicitCpu"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlSlotPolicyExplicitCpuInput", GoGetter: "HaAdmissionControlSlotPolicyExplicitCpuInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlSlotPolicyExplicitMemory", GoGetter: "HaAdmissionControlSlotPolicyExplicitMemory"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlSlotPolicyExplicitMemoryInput", GoGetter: "HaAdmissionControlSlotPolicyExplicitMemoryInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlSlotPolicyUseExplicitSize", GoGetter: "HaAdmissionControlSlotPolicyUseExplicitSize"},
			_jsii_.MemberProperty{JsiiProperty: "haAdmissionControlSlotPolicyUseExplicitSizeInput", GoGetter: "HaAdmissionControlSlotPolicyUseExplicitSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "haAdvancedOptions", GoGetter: "HaAdvancedOptions"},
			_jsii_.MemberProperty{JsiiProperty: "haAdvancedOptionsInput", GoGetter: "HaAdvancedOptionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "haDatastoreApdRecoveryAction", GoGetter: "HaDatastoreApdRecoveryAction"},
			_jsii_.MemberProperty{JsiiProperty: "haDatastoreApdRecoveryActionInput", GoGetter: "HaDatastoreApdRecoveryActionInput"},
			_jsii_.MemberProperty{JsiiProperty: "haDatastoreApdResponse", GoGetter: "HaDatastoreApdResponse"},
			_jsii_.MemberProperty{JsiiProperty: "haDatastoreApdResponseDelay", GoGetter: "HaDatastoreApdResponseDelay"},
			_jsii_.MemberProperty{JsiiProperty: "haDatastoreApdResponseDelayInput", GoGetter: "HaDatastoreApdResponseDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "haDatastoreApdResponseInput", GoGetter: "HaDatastoreApdResponseInput"},
			_jsii_.MemberProperty{JsiiProperty: "haDatastorePdlResponse", GoGetter: "HaDatastorePdlResponse"},
			_jsii_.MemberProperty{JsiiProperty: "haDatastorePdlResponseInput", GoGetter: "HaDatastorePdlResponseInput"},
			_jsii_.MemberProperty{JsiiProperty: "haEnabled", GoGetter: "HaEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "haEnabledInput", GoGetter: "HaEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "haHeartbeatDatastoreIds", GoGetter: "HaHeartbeatDatastoreIds"},
			_jsii_.MemberProperty{JsiiProperty: "haHeartbeatDatastoreIdsInput", GoGetter: "HaHeartbeatDatastoreIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "haHeartbeatDatastorePolicy", GoGetter: "HaHeartbeatDatastorePolicy"},
			_jsii_.MemberProperty{JsiiProperty: "haHeartbeatDatastorePolicyInput", GoGetter: "HaHeartbeatDatastorePolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "haHostIsolationResponse", GoGetter: "HaHostIsolationResponse"},
			_jsii_.MemberProperty{JsiiProperty: "haHostIsolationResponseInput", GoGetter: "HaHostIsolationResponseInput"},
			_jsii_.MemberProperty{JsiiProperty: "haHostMonitoring", GoGetter: "HaHostMonitoring"},
			_jsii_.MemberProperty{JsiiProperty: "haHostMonitoringInput", GoGetter: "HaHostMonitoringInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmComponentProtection", GoGetter: "HaVmComponentProtection"},
			_jsii_.MemberProperty{JsiiProperty: "haVmComponentProtectionInput", GoGetter: "HaVmComponentProtectionInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmDependencyRestartCondition", GoGetter: "HaVmDependencyRestartCondition"},
			_jsii_.MemberProperty{JsiiProperty: "haVmDependencyRestartConditionInput", GoGetter: "HaVmDependencyRestartConditionInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmFailureInterval", GoGetter: "HaVmFailureInterval"},
			_jsii_.MemberProperty{JsiiProperty: "haVmFailureIntervalInput", GoGetter: "HaVmFailureIntervalInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmMaximumFailureWindow", GoGetter: "HaVmMaximumFailureWindow"},
			_jsii_.MemberProperty{JsiiProperty: "haVmMaximumFailureWindowInput", GoGetter: "HaVmMaximumFailureWindowInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmMaximumResets", GoGetter: "HaVmMaximumResets"},
			_jsii_.MemberProperty{JsiiProperty: "haVmMaximumResetsInput", GoGetter: "HaVmMaximumResetsInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmMinimumUptime", GoGetter: "HaVmMinimumUptime"},
			_jsii_.MemberProperty{JsiiProperty: "haVmMinimumUptimeInput", GoGetter: "HaVmMinimumUptimeInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmMonitoring", GoGetter: "HaVmMonitoring"},
			_jsii_.MemberProperty{JsiiProperty: "haVmMonitoringInput", GoGetter: "HaVmMonitoringInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmRestartAdditionalDelay", GoGetter: "HaVmRestartAdditionalDelay"},
			_jsii_.MemberProperty{JsiiProperty: "haVmRestartAdditionalDelayInput", GoGetter: "HaVmRestartAdditionalDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmRestartPriority", GoGetter: "HaVmRestartPriority"},
			_jsii_.MemberProperty{JsiiProperty: "haVmRestartPriorityInput", GoGetter: "HaVmRestartPriorityInput"},
			_jsii_.MemberProperty{JsiiProperty: "haVmRestartTimeout", GoGetter: "HaVmRestartTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "haVmRestartTimeoutInput", GoGetter: "HaVmRestartTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "hostClusterExitTimeout", GoGetter: "HostClusterExitTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "hostClusterExitTimeoutInput", GoGetter: "HostClusterExitTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "hostManaged", GoGetter: "HostManaged"},
			_jsii_.MemberProperty{JsiiProperty: "hostManagedInput", GoGetter: "HostManagedInput"},
			_jsii_.MemberProperty{JsiiProperty: "hostSystemIds", GoGetter: "HostSystemIds"},
			_jsii_.MemberProperty{JsiiProperty: "hostSystemIdsInput", GoGetter: "HostSystemIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaAutomationLevel", GoGetter: "ProactiveHaAutomationLevel"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaAutomationLevelInput", GoGetter: "ProactiveHaAutomationLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaEnabled", GoGetter: "ProactiveHaEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaEnabledInput", GoGetter: "ProactiveHaEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaModerateRemediation", GoGetter: "ProactiveHaModerateRemediation"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaModerateRemediationInput", GoGetter: "ProactiveHaModerateRemediationInput"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaProviderIds", GoGetter: "ProactiveHaProviderIds"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaProviderIdsInput", GoGetter: "ProactiveHaProviderIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaSevereRemediation", GoGetter: "ProactiveHaSevereRemediation"},
			_jsii_.MemberProperty{JsiiProperty: "proactiveHaSevereRemediationInput", GoGetter: "ProactiveHaSevereRemediationInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putVsanDiskGroup", GoMethod: "PutVsanDiskGroup"},
			_jsii_.MemberMethod{JsiiMethod: "putVsanFaultDomains", GoMethod: "PutVsanFaultDomains"},
			_jsii_.MemberMethod{JsiiMethod: "putVsanStretchedCluster", GoMethod: "PutVsanStretchedCluster"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomAttributes", GoMethod: "ResetCustomAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "resetDpmAutomationLevel", GoMethod: "ResetDpmAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetDpmEnabled", GoMethod: "ResetDpmEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetDpmThreshold", GoMethod: "ResetDpmThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetDrsAdvancedOptions", GoMethod: "ResetDrsAdvancedOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetDrsAutomationLevel", GoMethod: "ResetDrsAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetDrsEnabled", GoMethod: "ResetDrsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetDrsEnablePredictiveDrs", GoMethod: "ResetDrsEnablePredictiveDrs"},
			_jsii_.MemberMethod{JsiiMethod: "resetDrsEnableVmOverrides", GoMethod: "ResetDrsEnableVmOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetDrsMigrationThreshold", GoMethod: "ResetDrsMigrationThreshold"},
			_jsii_.MemberMethod{JsiiMethod: "resetDrsScaleDescendantsShares", GoMethod: "ResetDrsScaleDescendantsShares"},
			_jsii_.MemberMethod{JsiiMethod: "resetFolder", GoMethod: "ResetFolder"},
			_jsii_.MemberMethod{JsiiMethod: "resetForceEvacuateOnDestroy", GoMethod: "ResetForceEvacuateOnDestroy"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlFailoverHostSystemIds", GoMethod: "ResetHaAdmissionControlFailoverHostSystemIds"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlHostFailureTolerance", GoMethod: "ResetHaAdmissionControlHostFailureTolerance"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlPerformanceTolerance", GoMethod: "ResetHaAdmissionControlPerformanceTolerance"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlPolicy", GoMethod: "ResetHaAdmissionControlPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlResourcePercentageAutoCompute", GoMethod: "ResetHaAdmissionControlResourcePercentageAutoCompute"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlResourcePercentageCpu", GoMethod: "ResetHaAdmissionControlResourcePercentageCpu"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlResourcePercentageMemory", GoMethod: "ResetHaAdmissionControlResourcePercentageMemory"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlSlotPolicyExplicitCpu", GoMethod: "ResetHaAdmissionControlSlotPolicyExplicitCpu"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlSlotPolicyExplicitMemory", GoMethod: "ResetHaAdmissionControlSlotPolicyExplicitMemory"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdmissionControlSlotPolicyUseExplicitSize", GoMethod: "ResetHaAdmissionControlSlotPolicyUseExplicitSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaAdvancedOptions", GoMethod: "ResetHaAdvancedOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaDatastoreApdRecoveryAction", GoMethod: "ResetHaDatastoreApdRecoveryAction"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaDatastoreApdResponse", GoMethod: "ResetHaDatastoreApdResponse"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaDatastoreApdResponseDelay", GoMethod: "ResetHaDatastoreApdResponseDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaDatastorePdlResponse", GoMethod: "ResetHaDatastorePdlResponse"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaEnabled", GoMethod: "ResetHaEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaHeartbeatDatastoreIds", GoMethod: "ResetHaHeartbeatDatastoreIds"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaHeartbeatDatastorePolicy", GoMethod: "ResetHaHeartbeatDatastorePolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaHostIsolationResponse", GoMethod: "ResetHaHostIsolationResponse"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaHostMonitoring", GoMethod: "ResetHaHostMonitoring"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmComponentProtection", GoMethod: "ResetHaVmComponentProtection"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmDependencyRestartCondition", GoMethod: "ResetHaVmDependencyRestartCondition"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmFailureInterval", GoMethod: "ResetHaVmFailureInterval"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmMaximumFailureWindow", GoMethod: "ResetHaVmMaximumFailureWindow"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmMaximumResets", GoMethod: "ResetHaVmMaximumResets"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmMinimumUptime", GoMethod: "ResetHaVmMinimumUptime"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmMonitoring", GoMethod: "ResetHaVmMonitoring"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmRestartAdditionalDelay", GoMethod: "ResetHaVmRestartAdditionalDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmRestartPriority", GoMethod: "ResetHaVmRestartPriority"},
			_jsii_.MemberMethod{JsiiMethod: "resetHaVmRestartTimeout", GoMethod: "ResetHaVmRestartTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetHostClusterExitTimeout", GoMethod: "ResetHostClusterExitTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetHostManaged", GoMethod: "ResetHostManaged"},
			_jsii_.MemberMethod{JsiiMethod: "resetHostSystemIds", GoMethod: "ResetHostSystemIds"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetProactiveHaAutomationLevel", GoMethod: "ResetProactiveHaAutomationLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetProactiveHaEnabled", GoMethod: "ResetProactiveHaEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetProactiveHaModerateRemediation", GoMethod: "ResetProactiveHaModerateRemediation"},
			_jsii_.MemberMethod{JsiiMethod: "resetProactiveHaProviderIds", GoMethod: "ResetProactiveHaProviderIds"},
			_jsii_.MemberMethod{JsiiMethod: "resetProactiveHaSevereRemediation", GoMethod: "ResetProactiveHaSevereRemediation"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanCompressionEnabled", GoMethod: "ResetVsanCompressionEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanDedupEnabled", GoMethod: "ResetVsanDedupEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanDiskGroup", GoMethod: "ResetVsanDiskGroup"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanDitEncryptionEnabled", GoMethod: "ResetVsanDitEncryptionEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanDitRekeyInterval", GoMethod: "ResetVsanDitRekeyInterval"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanEnabled", GoMethod: "ResetVsanEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanEsaEnabled", GoMethod: "ResetVsanEsaEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanFaultDomains", GoMethod: "ResetVsanFaultDomains"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanNetworkDiagnosticModeEnabled", GoMethod: "ResetVsanNetworkDiagnosticModeEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanPerformanceEnabled", GoMethod: "ResetVsanPerformanceEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanRemoteDatastoreIds", GoMethod: "ResetVsanRemoteDatastoreIds"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanStretchedCluster", GoMethod: "ResetVsanStretchedCluster"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanUnmapEnabled", GoMethod: "ResetVsanUnmapEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanVerboseModeEnabled", GoMethod: "ResetVsanVerboseModeEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "resourcePoolId", GoGetter: "ResourcePoolId"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "vsanCompressionEnabled", GoGetter: "VsanCompressionEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanCompressionEnabledInput", GoGetter: "VsanCompressionEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanDedupEnabled", GoGetter: "VsanDedupEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanDedupEnabledInput", GoGetter: "VsanDedupEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanDiskGroup", GoGetter: "VsanDiskGroup"},
			_jsii_.MemberProperty{JsiiProperty: "vsanDiskGroupInput", GoGetter: "VsanDiskGroupInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanDitEncryptionEnabled", GoGetter: "VsanDitEncryptionEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanDitEncryptionEnabledInput", GoGetter: "VsanDitEncryptionEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanDitRekeyInterval", GoGetter: "VsanDitRekeyInterval"},
			_jsii_.MemberProperty{JsiiProperty: "vsanDitRekeyIntervalInput", GoGetter: "VsanDitRekeyIntervalInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanEnabled", GoGetter: "VsanEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanEnabledInput", GoGetter: "VsanEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanEsaEnabled", GoGetter: "VsanEsaEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanEsaEnabledInput", GoGetter: "VsanEsaEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanFaultDomains", GoGetter: "VsanFaultDomains"},
			_jsii_.MemberProperty{JsiiProperty: "vsanFaultDomainsInput", GoGetter: "VsanFaultDomainsInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanNetworkDiagnosticModeEnabled", GoGetter: "VsanNetworkDiagnosticModeEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanNetworkDiagnosticModeEnabledInput", GoGetter: "VsanNetworkDiagnosticModeEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanPerformanceEnabled", GoGetter: "VsanPerformanceEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanPerformanceEnabledInput", GoGetter: "VsanPerformanceEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanRemoteDatastoreIds", GoGetter: "VsanRemoteDatastoreIds"},
			_jsii_.MemberProperty{JsiiProperty: "vsanRemoteDatastoreIdsInput", GoGetter: "VsanRemoteDatastoreIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanStretchedCluster", GoGetter: "VsanStretchedCluster"},
			_jsii_.MemberProperty{JsiiProperty: "vsanStretchedClusterInput", GoGetter: "VsanStretchedClusterInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanUnmapEnabled", GoGetter: "VsanUnmapEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanUnmapEnabledInput", GoGetter: "VsanUnmapEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanVerboseModeEnabled", GoGetter: "VsanVerboseModeEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vsanVerboseModeEnabledInput", GoGetter: "VsanVerboseModeEnabledInput"},
		},
		func() interface{} {
			j := jsiiProxy_ComputeCluster{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterConfig",
		reflect.TypeOf((*ComputeClusterConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanDiskGroup",
		reflect.TypeOf((*ComputeClusterVsanDiskGroup)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanDiskGroupList",
		reflect.TypeOf((*ComputeClusterVsanDiskGroupList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ComputeClusterVsanDiskGroupList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanDiskGroupOutputReference",
		reflect.TypeOf((*ComputeClusterVsanDiskGroupOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "cache", GoGetter: "Cache"},
			_jsii_.MemberProperty{JsiiProperty: "cacheInput", GoGetter: "CacheInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetCache", GoMethod: "ResetCache"},
			_jsii_.MemberMethod{JsiiMethod: "resetStorage", GoMethod: "ResetStorage"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "storage", GoGetter: "Storage"},
			_jsii_.MemberProperty{JsiiProperty: "storageInput", GoGetter: "StorageInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ComputeClusterVsanDiskGroupOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanFaultDomains",
		reflect.TypeOf((*ComputeClusterVsanFaultDomains)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanFaultDomainsFaultDomain",
		reflect.TypeOf((*ComputeClusterVsanFaultDomainsFaultDomain)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanFaultDomainsFaultDomainList",
		reflect.TypeOf((*ComputeClusterVsanFaultDomainsFaultDomainList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ComputeClusterVsanFaultDomainsFaultDomainList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanFaultDomainsFaultDomainOutputReference",
		reflect.TypeOf((*ComputeClusterVsanFaultDomainsFaultDomainOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "hostIds", GoGetter: "HostIds"},
			_jsii_.MemberProperty{JsiiProperty: "hostIdsInput", GoGetter: "HostIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ComputeClusterVsanFaultDomainsFaultDomainOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanFaultDomainsList",
		reflect.TypeOf((*ComputeClusterVsanFaultDomainsList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_ComputeClusterVsanFaultDomainsList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanFaultDomainsOutputReference",
		reflect.TypeOf((*ComputeClusterVsanFaultDomainsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "faultDomain", GoGetter: "FaultDomain"},
			_jsii_.MemberProperty{JsiiProperty: "faultDomainInput", GoGetter: "FaultDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "putFaultDomain", GoMethod: "PutFaultDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetFaultDomain", GoMethod: "ResetFaultDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_ComputeClusterVsanFaultDomainsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanStretchedCluster",
		reflect.TypeOf((*ComputeClusterVsanStretchedCluster)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.computeCluster.ComputeClusterVsanStretchedClusterOutputReference",
		reflect.TypeOf((*ComputeClusterVsanStretchedClusterOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "preferredFaultDomainHostIds", GoGetter: "PreferredFaultDomainHostIds"},
			_jsii_.MemberProperty{JsiiProperty: "preferredFaultDomainHostIdsInput", GoGetter: "PreferredFaultDomainHostIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "preferredFaultDomainName", GoGetter: "PreferredFaultDomainName"},
			_jsii_.MemberProperty{JsiiProperty: "preferredFaultDomainNameInput", GoGetter: "PreferredFaultDomainNameInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetPreferredFaultDomainName", GoMethod: "ResetPreferredFaultDomainName"},
			_jsii_.MemberMethod{JsiiMethod: "resetSecondaryFaultDomainName", GoMethod: "ResetSecondaryFaultDomainName"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "secondaryFaultDomainHostIds", GoGetter: "SecondaryFaultDomainHostIds"},
			_jsii_.MemberProperty{JsiiProperty: "secondaryFaultDomainHostIdsInput", GoGetter: "SecondaryFaultDomainHostIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "secondaryFaultDomainName", GoGetter: "SecondaryFaultDomainName"},
			_jsii_.MemberProperty{JsiiProperty: "secondaryFaultDomainNameInput", GoGetter: "SecondaryFaultDomainNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "witnessNode", GoGetter: "WitnessNode"},
			_jsii_.MemberProperty{JsiiProperty: "witnessNodeInput", GoGetter: "WitnessNodeInput"},
		},
		func() interface{} {
			j := jsiiProxy_ComputeClusterVsanStretchedClusterOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
