// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package virtualmachine

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachine",
		reflect.TypeOf((*VirtualMachine)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "alternateGuestName", GoGetter: "AlternateGuestName"},
			_jsii_.MemberProperty{JsiiProperty: "alternateGuestNameInput", GoGetter: "AlternateGuestNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "annotation", GoGetter: "Annotation"},
			_jsii_.MemberProperty{JsiiProperty: "annotationInput", GoGetter: "AnnotationInput"},
			_jsii_.MemberProperty{JsiiProperty: "bootDelay", GoGetter: "BootDelay"},
			_jsii_.MemberProperty{JsiiProperty: "bootDelayInput", GoGetter: "BootDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "bootRetryDelay", GoGetter: "BootRetryDelay"},
			_jsii_.MemberProperty{JsiiProperty: "bootRetryDelayInput", GoGetter: "BootRetryDelayInput"},
			_jsii_.MemberProperty{JsiiProperty: "bootRetryEnabled", GoGetter: "BootRetryEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "bootRetryEnabledInput", GoGetter: "BootRetryEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "cdrom", GoGetter: "Cdrom"},
			_jsii_.MemberProperty{JsiiProperty: "cdromInput", GoGetter: "CdromInput"},
			_jsii_.MemberProperty{JsiiProperty: "changeVersion", GoGetter: "ChangeVersion"},
			_jsii_.MemberProperty{JsiiProperty: "clone", GoGetter: "Clone"},
			_jsii_.MemberProperty{JsiiProperty: "cloneInput", GoGetter: "CloneInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "cpuHotAddEnabled", GoGetter: "CpuHotAddEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "cpuHotAddEnabledInput", GoGetter: "CpuHotAddEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuHotRemoveEnabled", GoGetter: "CpuHotRemoveEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "cpuHotRemoveEnabledInput", GoGetter: "CpuHotRemoveEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuLimit", GoGetter: "CpuLimit"},
			_jsii_.MemberProperty{JsiiProperty: "cpuLimitInput", GoGetter: "CpuLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuPerformanceCountersEnabled", GoGetter: "CpuPerformanceCountersEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "cpuPerformanceCountersEnabledInput", GoGetter: "CpuPerformanceCountersEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuReservation", GoGetter: "CpuReservation"},
			_jsii_.MemberProperty{JsiiProperty: "cpuReservationInput", GoGetter: "CpuReservationInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuShareCount", GoGetter: "CpuShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "cpuShareCountInput", GoGetter: "CpuShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "cpuShareLevel", GoGetter: "CpuShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "cpuShareLevelInput", GoGetter: "CpuShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributes", GoGetter: "CustomAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributesInput", GoGetter: "CustomAttributesInput"},
			_jsii_.MemberProperty{JsiiProperty: "datacenterId", GoGetter: "DatacenterId"},
			_jsii_.MemberProperty{JsiiProperty: "datacenterIdInput", GoGetter: "DatacenterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "datastoreClusterId", GoGetter: "DatastoreClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "datastoreClusterIdInput", GoGetter: "DatastoreClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "datastoreId", GoGetter: "DatastoreId"},
			_jsii_.MemberProperty{JsiiProperty: "datastoreIdInput", GoGetter: "DatastoreIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "defaultIpAddress", GoGetter: "DefaultIpAddress"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "disk", GoGetter: "Disk"},
			_jsii_.MemberProperty{JsiiProperty: "diskInput", GoGetter: "DiskInput"},
			_jsii_.MemberProperty{JsiiProperty: "efiSecureBootEnabled", GoGetter: "EfiSecureBootEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "efiSecureBootEnabledInput", GoGetter: "EfiSecureBootEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableDiskUuid", GoGetter: "EnableDiskUuid"},
			_jsii_.MemberProperty{JsiiProperty: "enableDiskUuidInput", GoGetter: "EnableDiskUuidInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableLogging", GoGetter: "EnableLogging"},
			_jsii_.MemberProperty{JsiiProperty: "enableLoggingInput", GoGetter: "EnableLoggingInput"},
			_jsii_.MemberProperty{JsiiProperty: "eptRviMode", GoGetter: "EptRviMode"},
			_jsii_.MemberProperty{JsiiProperty: "eptRviModeInput", GoGetter: "EptRviModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "extraConfig", GoGetter: "ExtraConfig"},
			_jsii_.MemberProperty{JsiiProperty: "extraConfigInput", GoGetter: "ExtraConfigInput"},
			_jsii_.MemberProperty{JsiiProperty: "extraConfigRebootRequired", GoGetter: "ExtraConfigRebootRequired"},
			_jsii_.MemberProperty{JsiiProperty: "extraConfigRebootRequiredInput", GoGetter: "ExtraConfigRebootRequiredInput"},
			_jsii_.MemberProperty{JsiiProperty: "firmware", GoGetter: "Firmware"},
			_jsii_.MemberProperty{JsiiProperty: "firmwareInput", GoGetter: "FirmwareInput"},
			_jsii_.MemberProperty{JsiiProperty: "folder", GoGetter: "Folder"},
			_jsii_.MemberProperty{JsiiProperty: "folderInput", GoGetter: "FolderInput"},
			_jsii_.MemberProperty{JsiiProperty: "forcePowerOff", GoGetter: "ForcePowerOff"},
			_jsii_.MemberProperty{JsiiProperty: "forcePowerOffInput", GoGetter: "ForcePowerOffInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "guestId", GoGetter: "GuestId"},
			_jsii_.MemberProperty{JsiiProperty: "guestIdInput", GoGetter: "GuestIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "guestIpAddresses", GoGetter: "GuestIpAddresses"},
			_jsii_.MemberProperty{JsiiProperty: "hardwareVersion", GoGetter: "HardwareVersion"},
			_jsii_.MemberProperty{JsiiProperty: "hardwareVersionInput", GoGetter: "HardwareVersionInput"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "hostSystemId", GoGetter: "HostSystemId"},
			_jsii_.MemberProperty{JsiiProperty: "hostSystemIdInput", GoGetter: "HostSystemIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "hvMode", GoGetter: "HvMode"},
			_jsii_.MemberProperty{JsiiProperty: "hvModeInput", GoGetter: "HvModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "ideControllerCount", GoGetter: "IdeControllerCount"},
			_jsii_.MemberProperty{JsiiProperty: "ideControllerCountInput", GoGetter: "IdeControllerCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "ignoredGuestIps", GoGetter: "IgnoredGuestIps"},
			_jsii_.MemberProperty{JsiiProperty: "ignoredGuestIpsInput", GoGetter: "IgnoredGuestIpsInput"},
			_jsii_.MemberProperty{JsiiProperty: "imported", GoGetter: "Imported"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "latencySensitivity", GoGetter: "LatencySensitivity"},
			_jsii_.MemberProperty{JsiiProperty: "latencySensitivityInput", GoGetter: "LatencySensitivityInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "memory", GoGetter: "Memory"},
			_jsii_.MemberProperty{JsiiProperty: "memoryHotAddEnabled", GoGetter: "MemoryHotAddEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "memoryHotAddEnabledInput", GoGetter: "MemoryHotAddEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryInput", GoGetter: "MemoryInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryLimit", GoGetter: "MemoryLimit"},
			_jsii_.MemberProperty{JsiiProperty: "memoryLimitInput", GoGetter: "MemoryLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryReservation", GoGetter: "MemoryReservation"},
			_jsii_.MemberProperty{JsiiProperty: "memoryReservationInput", GoGetter: "MemoryReservationInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryReservationLockedToMax", GoGetter: "MemoryReservationLockedToMax"},
			_jsii_.MemberProperty{JsiiProperty: "memoryReservationLockedToMaxInput", GoGetter: "MemoryReservationLockedToMaxInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryShareCount", GoGetter: "MemoryShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "memoryShareCountInput", GoGetter: "MemoryShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "memoryShareLevel", GoGetter: "MemoryShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "memoryShareLevelInput", GoGetter: "MemoryShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "migrateWaitTimeout", GoGetter: "MigrateWaitTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "migrateWaitTimeoutInput", GoGetter: "MigrateWaitTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "moid", GoGetter: "Moid"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "nestedHvEnabled", GoGetter: "NestedHvEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "nestedHvEnabledInput", GoGetter: "NestedHvEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkInterface", GoGetter: "NetworkInterface"},
			_jsii_.MemberProperty{JsiiProperty: "networkInterfaceInput", GoGetter: "NetworkInterfaceInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "numCoresPerSocket", GoGetter: "NumCoresPerSocket"},
			_jsii_.MemberProperty{JsiiProperty: "numCoresPerSocketInput", GoGetter: "NumCoresPerSocketInput"},
			_jsii_.MemberProperty{JsiiProperty: "numCpus", GoGetter: "NumCpus"},
			_jsii_.MemberProperty{JsiiProperty: "numCpusInput", GoGetter: "NumCpusInput"},
			_jsii_.MemberProperty{JsiiProperty: "nvmeControllerCount", GoGetter: "NvmeControllerCount"},
			_jsii_.MemberProperty{JsiiProperty: "nvmeControllerCountInput", GoGetter: "NvmeControllerCountInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "ovfDeploy", GoGetter: "OvfDeploy"},
			_jsii_.MemberProperty{JsiiProperty: "ovfDeployInput", GoGetter: "OvfDeployInput"},
			_jsii_.MemberProperty{JsiiProperty: "pciDeviceId", GoGetter: "PciDeviceId"},
			_jsii_.MemberProperty{JsiiProperty: "pciDeviceIdInput", GoGetter: "PciDeviceIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "poweronTimeout", GoGetter: "PoweronTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "poweronTimeoutInput", GoGetter: "PoweronTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "powerState", GoGetter: "PowerState"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putCdrom", GoMethod: "PutCdrom"},
			_jsii_.MemberMethod{JsiiMethod: "putClone", GoMethod: "PutClone"},
			_jsii_.MemberMethod{JsiiMethod: "putDisk", GoMethod: "PutDisk"},
			_jsii_.MemberMethod{JsiiMethod: "putNetworkInterface", GoMethod: "PutNetworkInterface"},
			_jsii_.MemberMethod{JsiiMethod: "putOvfDeploy", GoMethod: "PutOvfDeploy"},
			_jsii_.MemberMethod{JsiiMethod: "putVapp", GoMethod: "PutVapp"},
			_jsii_.MemberMethod{JsiiMethod: "putVtpm", GoMethod: "PutVtpm"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "rebootRequired", GoGetter: "RebootRequired"},
			_jsii_.MemberProperty{JsiiProperty: "replaceTrigger", GoGetter: "ReplaceTrigger"},
			_jsii_.MemberProperty{JsiiProperty: "replaceTriggerInput", GoGetter: "ReplaceTriggerInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAlternateGuestName", GoMethod: "ResetAlternateGuestName"},
			_jsii_.MemberMethod{JsiiMethod: "resetAnnotation", GoMethod: "ResetAnnotation"},
			_jsii_.MemberMethod{JsiiMethod: "resetBootDelay", GoMethod: "ResetBootDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetBootRetryDelay", GoMethod: "ResetBootRetryDelay"},
			_jsii_.MemberMethod{JsiiMethod: "resetBootRetryEnabled", GoMethod: "ResetBootRetryEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetCdrom", GoMethod: "ResetCdrom"},
			_jsii_.MemberMethod{JsiiMethod: "resetClone", GoMethod: "ResetClone"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuHotAddEnabled", GoMethod: "ResetCpuHotAddEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuHotRemoveEnabled", GoMethod: "ResetCpuHotRemoveEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuLimit", GoMethod: "ResetCpuLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuPerformanceCountersEnabled", GoMethod: "ResetCpuPerformanceCountersEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuReservation", GoMethod: "ResetCpuReservation"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuShareCount", GoMethod: "ResetCpuShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetCpuShareLevel", GoMethod: "ResetCpuShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomAttributes", GoMethod: "ResetCustomAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatacenterId", GoMethod: "ResetDatacenterId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatastoreClusterId", GoMethod: "ResetDatastoreClusterId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatastoreId", GoMethod: "ResetDatastoreId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDisk", GoMethod: "ResetDisk"},
			_jsii_.MemberMethod{JsiiMethod: "resetEfiSecureBootEnabled", GoMethod: "ResetEfiSecureBootEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableDiskUuid", GoMethod: "ResetEnableDiskUuid"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableLogging", GoMethod: "ResetEnableLogging"},
			_jsii_.MemberMethod{JsiiMethod: "resetEptRviMode", GoMethod: "ResetEptRviMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetExtraConfig", GoMethod: "ResetExtraConfig"},
			_jsii_.MemberMethod{JsiiMethod: "resetExtraConfigRebootRequired", GoMethod: "ResetExtraConfigRebootRequired"},
			_jsii_.MemberMethod{JsiiMethod: "resetFirmware", GoMethod: "ResetFirmware"},
			_jsii_.MemberMethod{JsiiMethod: "resetFolder", GoMethod: "ResetFolder"},
			_jsii_.MemberMethod{JsiiMethod: "resetForcePowerOff", GoMethod: "ResetForcePowerOff"},
			_jsii_.MemberMethod{JsiiMethod: "resetGuestId", GoMethod: "ResetGuestId"},
			_jsii_.MemberMethod{JsiiMethod: "resetHardwareVersion", GoMethod: "ResetHardwareVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetHostSystemId", GoMethod: "ResetHostSystemId"},
			_jsii_.MemberMethod{JsiiMethod: "resetHvMode", GoMethod: "ResetHvMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIdeControllerCount", GoMethod: "ResetIdeControllerCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoredGuestIps", GoMethod: "ResetIgnoredGuestIps"},
			_jsii_.MemberMethod{JsiiMethod: "resetLatencySensitivity", GoMethod: "ResetLatencySensitivity"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemory", GoMethod: "ResetMemory"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryHotAddEnabled", GoMethod: "ResetMemoryHotAddEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryLimit", GoMethod: "ResetMemoryLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryReservation", GoMethod: "ResetMemoryReservation"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryReservationLockedToMax", GoMethod: "ResetMemoryReservationLockedToMax"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryShareCount", GoMethod: "ResetMemoryShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetMemoryShareLevel", GoMethod: "ResetMemoryShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetMigrateWaitTimeout", GoMethod: "ResetMigrateWaitTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetNestedHvEnabled", GoMethod: "ResetNestedHvEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkInterface", GoMethod: "ResetNetworkInterface"},
			_jsii_.MemberMethod{JsiiMethod: "resetNumCoresPerSocket", GoMethod: "ResetNumCoresPerSocket"},
			_jsii_.MemberMethod{JsiiMethod: "resetNumCpus", GoMethod: "ResetNumCpus"},
			_jsii_.MemberMethod{JsiiMethod: "resetNvmeControllerCount", GoMethod: "ResetNvmeControllerCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOvfDeploy", GoMethod: "ResetOvfDeploy"},
			_jsii_.MemberMethod{JsiiMethod: "resetPciDeviceId", GoMethod: "ResetPciDeviceId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPoweronTimeout", GoMethod: "ResetPoweronTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetReplaceTrigger", GoMethod: "ResetReplaceTrigger"},
			_jsii_.MemberMethod{JsiiMethod: "resetRunToolsScriptsAfterPowerOn", GoMethod: "ResetRunToolsScriptsAfterPowerOn"},
			_jsii_.MemberMethod{JsiiMethod: "resetRunToolsScriptsAfterResume", GoMethod: "ResetRunToolsScriptsAfterResume"},
			_jsii_.MemberMethod{JsiiMethod: "resetRunToolsScriptsBeforeGuestReboot", GoMethod: "ResetRunToolsScriptsBeforeGuestReboot"},
			_jsii_.MemberMethod{JsiiMethod: "resetRunToolsScriptsBeforeGuestShutdown", GoMethod: "ResetRunToolsScriptsBeforeGuestShutdown"},
			_jsii_.MemberMethod{JsiiMethod: "resetRunToolsScriptsBeforeGuestStandby", GoMethod: "ResetRunToolsScriptsBeforeGuestStandby"},
			_jsii_.MemberMethod{JsiiMethod: "resetSataControllerCount", GoMethod: "ResetSataControllerCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetScsiBusSharing", GoMethod: "ResetScsiBusSharing"},
			_jsii_.MemberMethod{JsiiMethod: "resetScsiControllerCount", GoMethod: "ResetScsiControllerCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetScsiType", GoMethod: "ResetScsiType"},
			_jsii_.MemberMethod{JsiiMethod: "resetShutdownWaitTimeout", GoMethod: "ResetShutdownWaitTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetStoragePolicyId", GoMethod: "ResetStoragePolicyId"},
			_jsii_.MemberMethod{JsiiMethod: "resetSwapPlacementPolicy", GoMethod: "ResetSwapPlacementPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncTimeWithHost", GoMethod: "ResetSyncTimeWithHost"},
			_jsii_.MemberMethod{JsiiMethod: "resetSyncTimeWithHostPeriodically", GoMethod: "ResetSyncTimeWithHostPeriodically"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberMethod{JsiiMethod: "resetToolsUpgradePolicy", GoMethod: "ResetToolsUpgradePolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetVapp", GoMethod: "ResetVapp"},
			_jsii_.MemberMethod{JsiiMethod: "resetVbsEnabled", GoMethod: "ResetVbsEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetVtpm", GoMethod: "ResetVtpm"},
			_jsii_.MemberMethod{JsiiMethod: "resetVvtdEnabled", GoMethod: "ResetVvtdEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetWaitForGuestIpTimeout", GoMethod: "ResetWaitForGuestIpTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetWaitForGuestNetRoutable", GoMethod: "ResetWaitForGuestNetRoutable"},
			_jsii_.MemberMethod{JsiiMethod: "resetWaitForGuestNetTimeout", GoMethod: "ResetWaitForGuestNetTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "resourcePoolId", GoGetter: "ResourcePoolId"},
			_jsii_.MemberProperty{JsiiProperty: "resourcePoolIdInput", GoGetter: "ResourcePoolIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsAfterPowerOn", GoGetter: "RunToolsScriptsAfterPowerOn"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsAfterPowerOnInput", GoGetter: "RunToolsScriptsAfterPowerOnInput"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsAfterResume", GoGetter: "RunToolsScriptsAfterResume"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsAfterResumeInput", GoGetter: "RunToolsScriptsAfterResumeInput"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsBeforeGuestReboot", GoGetter: "RunToolsScriptsBeforeGuestReboot"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsBeforeGuestRebootInput", GoGetter: "RunToolsScriptsBeforeGuestRebootInput"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsBeforeGuestShutdown", GoGetter: "RunToolsScriptsBeforeGuestShutdown"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsBeforeGuestShutdownInput", GoGetter: "RunToolsScriptsBeforeGuestShutdownInput"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsBeforeGuestStandby", GoGetter: "RunToolsScriptsBeforeGuestStandby"},
			_jsii_.MemberProperty{JsiiProperty: "runToolsScriptsBeforeGuestStandbyInput", GoGetter: "RunToolsScriptsBeforeGuestStandbyInput"},
			_jsii_.MemberProperty{JsiiProperty: "sataControllerCount", GoGetter: "SataControllerCount"},
			_jsii_.MemberProperty{JsiiProperty: "sataControllerCountInput", GoGetter: "SataControllerCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "scsiBusSharing", GoGetter: "ScsiBusSharing"},
			_jsii_.MemberProperty{JsiiProperty: "scsiBusSharingInput", GoGetter: "ScsiBusSharingInput"},
			_jsii_.MemberProperty{JsiiProperty: "scsiControllerCount", GoGetter: "ScsiControllerCount"},
			_jsii_.MemberProperty{JsiiProperty: "scsiControllerCountInput", GoGetter: "ScsiControllerCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "scsiType", GoGetter: "ScsiType"},
			_jsii_.MemberProperty{JsiiProperty: "scsiTypeInput", GoGetter: "ScsiTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "shutdownWaitTimeout", GoGetter: "ShutdownWaitTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "shutdownWaitTimeoutInput", GoGetter: "ShutdownWaitTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "storagePolicyId", GoGetter: "StoragePolicyId"},
			_jsii_.MemberProperty{JsiiProperty: "storagePolicyIdInput", GoGetter: "StoragePolicyIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "swapPlacementPolicy", GoGetter: "SwapPlacementPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "swapPlacementPolicyInput", GoGetter: "SwapPlacementPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncTimeWithHost", GoGetter: "SyncTimeWithHost"},
			_jsii_.MemberProperty{JsiiProperty: "syncTimeWithHostInput", GoGetter: "SyncTimeWithHostInput"},
			_jsii_.MemberProperty{JsiiProperty: "syncTimeWithHostPeriodically", GoGetter: "SyncTimeWithHostPeriodically"},
			_jsii_.MemberProperty{JsiiProperty: "syncTimeWithHostPeriodicallyInput", GoGetter: "SyncTimeWithHostPeriodicallyInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "toolsUpgradePolicy", GoGetter: "ToolsUpgradePolicy"},
			_jsii_.MemberProperty{JsiiProperty: "toolsUpgradePolicyInput", GoGetter: "ToolsUpgradePolicyInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "uuid", GoGetter: "Uuid"},
			_jsii_.MemberProperty{JsiiProperty: "vapp", GoGetter: "Vapp"},
			_jsii_.MemberProperty{JsiiProperty: "vappInput", GoGetter: "VappInput"},
			_jsii_.MemberProperty{JsiiProperty: "vappTransport", GoGetter: "VappTransport"},
			_jsii_.MemberProperty{JsiiProperty: "vbsEnabled", GoGetter: "VbsEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vbsEnabledInput", GoGetter: "VbsEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmwareToolsStatus", GoGetter: "VmwareToolsStatus"},
			_jsii_.MemberProperty{JsiiProperty: "vmxPath", GoGetter: "VmxPath"},
			_jsii_.MemberProperty{JsiiProperty: "vtpm", GoGetter: "Vtpm"},
			_jsii_.MemberProperty{JsiiProperty: "vtpmInput", GoGetter: "VtpmInput"},
			_jsii_.MemberProperty{JsiiProperty: "vvtdEnabled", GoGetter: "VvtdEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "vvtdEnabledInput", GoGetter: "VvtdEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "waitForGuestIpTimeout", GoGetter: "WaitForGuestIpTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "waitForGuestIpTimeoutInput", GoGetter: "WaitForGuestIpTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "waitForGuestNetRoutable", GoGetter: "WaitForGuestNetRoutable"},
			_jsii_.MemberProperty{JsiiProperty: "waitForGuestNetRoutableInput", GoGetter: "WaitForGuestNetRoutableInput"},
			_jsii_.MemberProperty{JsiiProperty: "waitForGuestNetTimeout", GoGetter: "WaitForGuestNetTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "waitForGuestNetTimeoutInput", GoGetter: "WaitForGuestNetTimeoutInput"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachine{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCdrom",
		reflect.TypeOf((*VirtualMachineCdrom)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCdromList",
		reflect.TypeOf((*VirtualMachineCdromList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCdromList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCdromOutputReference",
		reflect.TypeOf((*VirtualMachineCdromOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "clientDevice", GoGetter: "ClientDevice"},
			_jsii_.MemberProperty{JsiiProperty: "clientDeviceInput", GoGetter: "ClientDeviceInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "datastoreId", GoGetter: "DatastoreId"},
			_jsii_.MemberProperty{JsiiProperty: "datastoreIdInput", GoGetter: "DatastoreIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "deviceAddress", GoGetter: "DeviceAddress"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "key", GoGetter: "Key"},
			_jsii_.MemberProperty{JsiiProperty: "path", GoGetter: "Path"},
			_jsii_.MemberProperty{JsiiProperty: "pathInput", GoGetter: "PathInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetClientDevice", GoMethod: "ResetClientDevice"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatastoreId", GoMethod: "ResetDatastoreId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPath", GoMethod: "ResetPath"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCdromOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineClone",
		reflect.TypeOf((*VirtualMachineClone)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizationSpec",
		reflect.TypeOf((*VirtualMachineCloneCustomizationSpec)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizationSpecOutputReference",
		reflect.TypeOf((*VirtualMachineCloneCustomizationSpecOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeout", GoMethod: "ResetTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timeout", GoGetter: "Timeout"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutInput", GoGetter: "TimeoutInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCloneCustomizationSpecOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomize",
		reflect.TypeOf((*VirtualMachineCloneCustomize)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizeLinuxOptions",
		reflect.TypeOf((*VirtualMachineCloneCustomizeLinuxOptions)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizeLinuxOptionsOutputReference",
		reflect.TypeOf((*VirtualMachineCloneCustomizeLinuxOptionsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "domain", GoGetter: "Domain"},
			_jsii_.MemberProperty{JsiiProperty: "domainInput", GoGetter: "DomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "hostName", GoGetter: "HostName"},
			_jsii_.MemberProperty{JsiiProperty: "hostNameInput", GoGetter: "HostNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "hwClockUtc", GoGetter: "HwClockUtc"},
			_jsii_.MemberProperty{JsiiProperty: "hwClockUtcInput", GoGetter: "HwClockUtcInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetHwClockUtc", GoMethod: "ResetHwClockUtc"},
			_jsii_.MemberMethod{JsiiMethod: "resetScriptText", GoMethod: "ResetScriptText"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeZone", GoMethod: "ResetTimeZone"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "scriptText", GoGetter: "ScriptText"},
			_jsii_.MemberProperty{JsiiProperty: "scriptTextInput", GoGetter: "ScriptTextInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timeZone", GoGetter: "TimeZone"},
			_jsii_.MemberProperty{JsiiProperty: "timeZoneInput", GoGetter: "TimeZoneInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCloneCustomizeLinuxOptionsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizeNetworkInterface",
		reflect.TypeOf((*VirtualMachineCloneCustomizeNetworkInterface)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizeNetworkInterfaceList",
		reflect.TypeOf((*VirtualMachineCloneCustomizeNetworkInterfaceList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCloneCustomizeNetworkInterfaceList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizeNetworkInterfaceOutputReference",
		reflect.TypeOf((*VirtualMachineCloneCustomizeNetworkInterfaceOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dnsDomain", GoGetter: "DnsDomain"},
			_jsii_.MemberProperty{JsiiProperty: "dnsDomainInput", GoGetter: "DnsDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "dnsServerList", GoGetter: "DnsServerList"},
			_jsii_.MemberProperty{JsiiProperty: "dnsServerListInput", GoGetter: "DnsServerListInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4Address", GoGetter: "Ipv4Address"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4AddressInput", GoGetter: "Ipv4AddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4Netmask", GoGetter: "Ipv4Netmask"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4NetmaskInput", GoGetter: "Ipv4NetmaskInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6Address", GoGetter: "Ipv6Address"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6AddressInput", GoGetter: "Ipv6AddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6Netmask", GoGetter: "Ipv6Netmask"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6NetmaskInput", GoGetter: "Ipv6NetmaskInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetDnsDomain", GoMethod: "ResetDnsDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetDnsServerList", GoMethod: "ResetDnsServerList"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv4Address", GoMethod: "ResetIpv4Address"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv4Netmask", GoMethod: "ResetIpv4Netmask"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv6Address", GoMethod: "ResetIpv6Address"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv6Netmask", GoMethod: "ResetIpv6Netmask"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCloneCustomizeNetworkInterfaceOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizeOutputReference",
		reflect.TypeOf((*VirtualMachineCloneCustomizeOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "dnsServerList", GoGetter: "DnsServerList"},
			_jsii_.MemberProperty{JsiiProperty: "dnsServerListInput", GoGetter: "DnsServerListInput"},
			_jsii_.MemberProperty{JsiiProperty: "dnsSuffixList", GoGetter: "DnsSuffixList"},
			_jsii_.MemberProperty{JsiiProperty: "dnsSuffixListInput", GoGetter: "DnsSuffixListInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4Gateway", GoGetter: "Ipv4Gateway"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4GatewayInput", GoGetter: "Ipv4GatewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6Gateway", GoGetter: "Ipv6Gateway"},
			_jsii_.MemberProperty{JsiiProperty: "ipv6GatewayInput", GoGetter: "Ipv6GatewayInput"},
			_jsii_.MemberProperty{JsiiProperty: "linuxOptions", GoGetter: "LinuxOptions"},
			_jsii_.MemberProperty{JsiiProperty: "linuxOptionsInput", GoGetter: "LinuxOptionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkInterface", GoGetter: "NetworkInterface"},
			_jsii_.MemberProperty{JsiiProperty: "networkInterfaceInput", GoGetter: "NetworkInterfaceInput"},
			_jsii_.MemberMethod{JsiiMethod: "putLinuxOptions", GoMethod: "PutLinuxOptions"},
			_jsii_.MemberMethod{JsiiMethod: "putNetworkInterface", GoMethod: "PutNetworkInterface"},
			_jsii_.MemberMethod{JsiiMethod: "putWindowsOptions", GoMethod: "PutWindowsOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetDnsServerList", GoMethod: "ResetDnsServerList"},
			_jsii_.MemberMethod{JsiiMethod: "resetDnsSuffixList", GoMethod: "ResetDnsSuffixList"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv4Gateway", GoMethod: "ResetIpv4Gateway"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv6Gateway", GoMethod: "ResetIpv6Gateway"},
			_jsii_.MemberMethod{JsiiMethod: "resetLinuxOptions", GoMethod: "ResetLinuxOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkInterface", GoMethod: "ResetNetworkInterface"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeout", GoMethod: "ResetTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetWindowsOptions", GoMethod: "ResetWindowsOptions"},
			_jsii_.MemberMethod{JsiiMethod: "resetWindowsSysprepText", GoMethod: "ResetWindowsSysprepText"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timeout", GoGetter: "Timeout"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutInput", GoGetter: "TimeoutInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "windowsOptions", GoGetter: "WindowsOptions"},
			_jsii_.MemberProperty{JsiiProperty: "windowsOptionsInput", GoGetter: "WindowsOptionsInput"},
			_jsii_.MemberProperty{JsiiProperty: "windowsSysprepText", GoGetter: "WindowsSysprepText"},
			_jsii_.MemberProperty{JsiiProperty: "windowsSysprepTextInput", GoGetter: "WindowsSysprepTextInput"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCloneCustomizeOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizeWindowsOptions",
		reflect.TypeOf((*VirtualMachineCloneCustomizeWindowsOptions)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneCustomizeWindowsOptionsOutputReference",
		reflect.TypeOf((*VirtualMachineCloneCustomizeWindowsOptionsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "adminPassword", GoGetter: "AdminPassword"},
			_jsii_.MemberProperty{JsiiProperty: "adminPasswordInput", GoGetter: "AdminPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "autoLogon", GoGetter: "AutoLogon"},
			_jsii_.MemberProperty{JsiiProperty: "autoLogonCount", GoGetter: "AutoLogonCount"},
			_jsii_.MemberProperty{JsiiProperty: "autoLogonCountInput", GoGetter: "AutoLogonCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "autoLogonInput", GoGetter: "AutoLogonInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "computerName", GoGetter: "ComputerName"},
			_jsii_.MemberProperty{JsiiProperty: "computerNameInput", GoGetter: "ComputerNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "domainAdminPassword", GoGetter: "DomainAdminPassword"},
			_jsii_.MemberProperty{JsiiProperty: "domainAdminPasswordInput", GoGetter: "DomainAdminPasswordInput"},
			_jsii_.MemberProperty{JsiiProperty: "domainAdminUser", GoGetter: "DomainAdminUser"},
			_jsii_.MemberProperty{JsiiProperty: "domainAdminUserInput", GoGetter: "DomainAdminUserInput"},
			_jsii_.MemberProperty{JsiiProperty: "domainOu", GoGetter: "DomainOu"},
			_jsii_.MemberProperty{JsiiProperty: "domainOuInput", GoGetter: "DomainOuInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "fullName", GoGetter: "FullName"},
			_jsii_.MemberProperty{JsiiProperty: "fullNameInput", GoGetter: "FullNameInput"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomain", GoGetter: "JoinDomain"},
			_jsii_.MemberProperty{JsiiProperty: "joinDomainInput", GoGetter: "JoinDomainInput"},
			_jsii_.MemberProperty{JsiiProperty: "organizationName", GoGetter: "OrganizationName"},
			_jsii_.MemberProperty{JsiiProperty: "organizationNameInput", GoGetter: "OrganizationNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "productKey", GoGetter: "ProductKey"},
			_jsii_.MemberProperty{JsiiProperty: "productKeyInput", GoGetter: "ProductKeyInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAdminPassword", GoMethod: "ResetAdminPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutoLogon", GoMethod: "ResetAutoLogon"},
			_jsii_.MemberMethod{JsiiMethod: "resetAutoLogonCount", GoMethod: "ResetAutoLogonCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetDomainAdminPassword", GoMethod: "ResetDomainAdminPassword"},
			_jsii_.MemberMethod{JsiiMethod: "resetDomainAdminUser", GoMethod: "ResetDomainAdminUser"},
			_jsii_.MemberMethod{JsiiMethod: "resetDomainOu", GoMethod: "ResetDomainOu"},
			_jsii_.MemberMethod{JsiiMethod: "resetFullName", GoMethod: "ResetFullName"},
			_jsii_.MemberMethod{JsiiMethod: "resetJoinDomain", GoMethod: "ResetJoinDomain"},
			_jsii_.MemberMethod{JsiiMethod: "resetOrganizationName", GoMethod: "ResetOrganizationName"},
			_jsii_.MemberMethod{JsiiMethod: "resetProductKey", GoMethod: "ResetProductKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetRunOnceCommandList", GoMethod: "ResetRunOnceCommandList"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeZone", GoMethod: "ResetTimeZone"},
			_jsii_.MemberMethod{JsiiMethod: "resetWorkgroup", GoMethod: "ResetWorkgroup"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "runOnceCommandList", GoGetter: "RunOnceCommandList"},
			_jsii_.MemberProperty{JsiiProperty: "runOnceCommandListInput", GoGetter: "RunOnceCommandListInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timeZone", GoGetter: "TimeZone"},
			_jsii_.MemberProperty{JsiiProperty: "timeZoneInput", GoGetter: "TimeZoneInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "workgroup", GoGetter: "Workgroup"},
			_jsii_.MemberProperty{JsiiProperty: "workgroupInput", GoGetter: "WorkgroupInput"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCloneCustomizeWindowsOptionsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineCloneOutputReference",
		reflect.TypeOf((*VirtualMachineCloneOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "customizationSpec", GoGetter: "CustomizationSpec"},
			_jsii_.MemberProperty{JsiiProperty: "customizationSpecInput", GoGetter: "CustomizationSpecInput"},
			_jsii_.MemberProperty{JsiiProperty: "customize", GoGetter: "Customize"},
			_jsii_.MemberProperty{JsiiProperty: "customizeInput", GoGetter: "CustomizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "linkedClone", GoGetter: "LinkedClone"},
			_jsii_.MemberProperty{JsiiProperty: "linkedCloneInput", GoGetter: "LinkedCloneInput"},
			_jsii_.MemberProperty{JsiiProperty: "ovfNetworkMap", GoGetter: "OvfNetworkMap"},
			_jsii_.MemberProperty{JsiiProperty: "ovfNetworkMapInput", GoGetter: "OvfNetworkMapInput"},
			_jsii_.MemberProperty{JsiiProperty: "ovfStorageMap", GoGetter: "OvfStorageMap"},
			_jsii_.MemberProperty{JsiiProperty: "ovfStorageMapInput", GoGetter: "OvfStorageMapInput"},
			_jsii_.MemberMethod{JsiiMethod: "putCustomizationSpec", GoMethod: "PutCustomizationSpec"},
			_jsii_.MemberMethod{JsiiMethod: "putCustomize", GoMethod: "PutCustomize"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomizationSpec", GoMethod: "ResetCustomizationSpec"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomize", GoMethod: "ResetCustomize"},
			_jsii_.MemberMethod{JsiiMethod: "resetLinkedClone", GoMethod: "ResetLinkedClone"},
			_jsii_.MemberMethod{JsiiMethod: "resetOvfNetworkMap", GoMethod: "ResetOvfNetworkMap"},
			_jsii_.MemberMethod{JsiiMethod: "resetOvfStorageMap", GoMethod: "ResetOvfStorageMap"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeout", GoMethod: "ResetTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "templateUuid", GoGetter: "TemplateUuid"},
			_jsii_.MemberProperty{JsiiProperty: "templateUuidInput", GoGetter: "TemplateUuidInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timeout", GoGetter: "Timeout"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutInput", GoGetter: "TimeoutInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineCloneOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineConfig",
		reflect.TypeOf((*VirtualMachineConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineDisk",
		reflect.TypeOf((*VirtualMachineDisk)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineDiskList",
		reflect.TypeOf((*VirtualMachineDiskList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineDiskList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineDiskOutputReference",
		reflect.TypeOf((*VirtualMachineDiskOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "attach", GoGetter: "Attach"},
			_jsii_.MemberProperty{JsiiProperty: "attachInput", GoGetter: "AttachInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "controllerType", GoGetter: "ControllerType"},
			_jsii_.MemberProperty{JsiiProperty: "controllerTypeInput", GoGetter: "ControllerTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "datastoreId", GoGetter: "DatastoreId"},
			_jsii_.MemberProperty{JsiiProperty: "datastoreIdInput", GoGetter: "DatastoreIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "deviceAddress", GoGetter: "DeviceAddress"},
			_jsii_.MemberProperty{JsiiProperty: "diskMode", GoGetter: "DiskMode"},
			_jsii_.MemberProperty{JsiiProperty: "diskModeInput", GoGetter: "DiskModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "diskSharing", GoGetter: "DiskSharing"},
			_jsii_.MemberProperty{JsiiProperty: "diskSharingInput", GoGetter: "DiskSharingInput"},
			_jsii_.MemberProperty{JsiiProperty: "eagerlyScrub", GoGetter: "EagerlyScrub"},
			_jsii_.MemberProperty{JsiiProperty: "eagerlyScrubInput", GoGetter: "EagerlyScrubInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ioLimit", GoGetter: "IoLimit"},
			_jsii_.MemberProperty{JsiiProperty: "ioLimitInput", GoGetter: "IoLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "ioReservation", GoGetter: "IoReservation"},
			_jsii_.MemberProperty{JsiiProperty: "ioReservationInput", GoGetter: "IoReservationInput"},
			_jsii_.MemberProperty{JsiiProperty: "ioShareCount", GoGetter: "IoShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "ioShareCountInput", GoGetter: "IoShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "ioShareLevel", GoGetter: "IoShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "ioShareLevelInput", GoGetter: "IoShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "keepOnRemove", GoGetter: "KeepOnRemove"},
			_jsii_.MemberProperty{JsiiProperty: "keepOnRemoveInput", GoGetter: "KeepOnRemoveInput"},
			_jsii_.MemberProperty{JsiiProperty: "key", GoGetter: "Key"},
			_jsii_.MemberProperty{JsiiProperty: "label", GoGetter: "Label"},
			_jsii_.MemberProperty{JsiiProperty: "labelInput", GoGetter: "LabelInput"},
			_jsii_.MemberProperty{JsiiProperty: "path", GoGetter: "Path"},
			_jsii_.MemberProperty{JsiiProperty: "pathInput", GoGetter: "PathInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAttach", GoMethod: "ResetAttach"},
			_jsii_.MemberMethod{JsiiMethod: "resetControllerType", GoMethod: "ResetControllerType"},
			_jsii_.MemberMethod{JsiiMethod: "resetDatastoreId", GoMethod: "ResetDatastoreId"},
			_jsii_.MemberMethod{JsiiMethod: "resetDiskMode", GoMethod: "ResetDiskMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetDiskSharing", GoMethod: "ResetDiskSharing"},
			_jsii_.MemberMethod{JsiiMethod: "resetEagerlyScrub", GoMethod: "ResetEagerlyScrub"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoLimit", GoMethod: "ResetIoLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoReservation", GoMethod: "ResetIoReservation"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoShareCount", GoMethod: "ResetIoShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetIoShareLevel", GoMethod: "ResetIoShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetKeepOnRemove", GoMethod: "ResetKeepOnRemove"},
			_jsii_.MemberMethod{JsiiMethod: "resetPath", GoMethod: "ResetPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetSize", GoMethod: "ResetSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetStoragePolicyId", GoMethod: "ResetStoragePolicyId"},
			_jsii_.MemberMethod{JsiiMethod: "resetThinProvisioned", GoMethod: "ResetThinProvisioned"},
			_jsii_.MemberMethod{JsiiMethod: "resetUnitNumber", GoMethod: "ResetUnitNumber"},
			_jsii_.MemberMethod{JsiiMethod: "resetWriteThrough", GoMethod: "ResetWriteThrough"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "size", GoGetter: "Size"},
			_jsii_.MemberProperty{JsiiProperty: "sizeInput", GoGetter: "SizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "storagePolicyId", GoGetter: "StoragePolicyId"},
			_jsii_.MemberProperty{JsiiProperty: "storagePolicyIdInput", GoGetter: "StoragePolicyIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "thinProvisioned", GoGetter: "ThinProvisioned"},
			_jsii_.MemberProperty{JsiiProperty: "thinProvisionedInput", GoGetter: "ThinProvisionedInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "unitNumber", GoGetter: "UnitNumber"},
			_jsii_.MemberProperty{JsiiProperty: "unitNumberInput", GoGetter: "UnitNumberInput"},
			_jsii_.MemberProperty{JsiiProperty: "uuid", GoGetter: "Uuid"},
			_jsii_.MemberProperty{JsiiProperty: "writeThrough", GoGetter: "WriteThrough"},
			_jsii_.MemberProperty{JsiiProperty: "writeThroughInput", GoGetter: "WriteThroughInput"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineDiskOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineNetworkInterface",
		reflect.TypeOf((*VirtualMachineNetworkInterface)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineNetworkInterfaceList",
		reflect.TypeOf((*VirtualMachineNetworkInterfaceList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineNetworkInterfaceList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineNetworkInterfaceOutputReference",
		reflect.TypeOf((*VirtualMachineNetworkInterfaceOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "adapterType", GoGetter: "AdapterType"},
			_jsii_.MemberProperty{JsiiProperty: "adapterTypeInput", GoGetter: "AdapterTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthLimit", GoGetter: "BandwidthLimit"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthLimitInput", GoGetter: "BandwidthLimitInput"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthReservation", GoGetter: "BandwidthReservation"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthReservationInput", GoGetter: "BandwidthReservationInput"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthShareCount", GoGetter: "BandwidthShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthShareCountInput", GoGetter: "BandwidthShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthShareLevel", GoGetter: "BandwidthShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthShareLevelInput", GoGetter: "BandwidthShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "deviceAddress", GoGetter: "DeviceAddress"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "key", GoGetter: "Key"},
			_jsii_.MemberProperty{JsiiProperty: "macAddress", GoGetter: "MacAddress"},
			_jsii_.MemberProperty{JsiiProperty: "macAddressInput", GoGetter: "MacAddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkId", GoGetter: "NetworkId"},
			_jsii_.MemberProperty{JsiiProperty: "networkIdInput", GoGetter: "NetworkIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "ovfMapping", GoGetter: "OvfMapping"},
			_jsii_.MemberProperty{JsiiProperty: "ovfMappingInput", GoGetter: "OvfMappingInput"},
			_jsii_.MemberProperty{JsiiProperty: "physicalFunction", GoGetter: "PhysicalFunction"},
			_jsii_.MemberProperty{JsiiProperty: "physicalFunctionInput", GoGetter: "PhysicalFunctionInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAdapterType", GoMethod: "ResetAdapterType"},
			_jsii_.MemberMethod{JsiiMethod: "resetBandwidthLimit", GoMethod: "ResetBandwidthLimit"},
			_jsii_.MemberMethod{JsiiMethod: "resetBandwidthReservation", GoMethod: "ResetBandwidthReservation"},
			_jsii_.MemberMethod{JsiiMethod: "resetBandwidthShareCount", GoMethod: "ResetBandwidthShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetBandwidthShareLevel", GoMethod: "ResetBandwidthShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetMacAddress", GoMethod: "ResetMacAddress"},
			_jsii_.MemberMethod{JsiiMethod: "resetOvfMapping", GoMethod: "ResetOvfMapping"},
			_jsii_.MemberMethod{JsiiMethod: "resetPhysicalFunction", GoMethod: "ResetPhysicalFunction"},
			_jsii_.MemberMethod{JsiiMethod: "resetUseStaticMac", GoMethod: "ResetUseStaticMac"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "useStaticMac", GoGetter: "UseStaticMac"},
			_jsii_.MemberProperty{JsiiProperty: "useStaticMacInput", GoGetter: "UseStaticMacInput"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineNetworkInterfaceOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineOvfDeploy",
		reflect.TypeOf((*VirtualMachineOvfDeploy)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineOvfDeployOutputReference",
		reflect.TypeOf((*VirtualMachineOvfDeployOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "allowUnverifiedSslCert", GoGetter: "AllowUnverifiedSslCert"},
			_jsii_.MemberProperty{JsiiProperty: "allowUnverifiedSslCertInput", GoGetter: "AllowUnverifiedSslCertInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "deploymentOption", GoGetter: "DeploymentOption"},
			_jsii_.MemberProperty{JsiiProperty: "deploymentOptionInput", GoGetter: "DeploymentOptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "diskProvisioning", GoGetter: "DiskProvisioning"},
			_jsii_.MemberProperty{JsiiProperty: "diskProvisioningInput", GoGetter: "DiskProvisioningInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableHiddenProperties", GoGetter: "EnableHiddenProperties"},
			_jsii_.MemberProperty{JsiiProperty: "enableHiddenPropertiesInput", GoGetter: "EnableHiddenPropertiesInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipAllocationPolicy", GoGetter: "IpAllocationPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "ipAllocationPolicyInput", GoGetter: "IpAllocationPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "ipProtocol", GoGetter: "IpProtocol"},
			_jsii_.MemberProperty{JsiiProperty: "ipProtocolInput", GoGetter: "IpProtocolInput"},
			_jsii_.MemberProperty{JsiiProperty: "localOvfPath", GoGetter: "LocalOvfPath"},
			_jsii_.MemberProperty{JsiiProperty: "localOvfPathInput", GoGetter: "LocalOvfPathInput"},
			_jsii_.MemberProperty{JsiiProperty: "ovfNetworkMap", GoGetter: "OvfNetworkMap"},
			_jsii_.MemberProperty{JsiiProperty: "ovfNetworkMapInput", GoGetter: "OvfNetworkMapInput"},
			_jsii_.MemberProperty{JsiiProperty: "remoteOvfUrl", GoGetter: "RemoteOvfUrl"},
			_jsii_.MemberProperty{JsiiProperty: "remoteOvfUrlInput", GoGetter: "RemoteOvfUrlInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowUnverifiedSslCert", GoMethod: "ResetAllowUnverifiedSslCert"},
			_jsii_.MemberMethod{JsiiMethod: "resetDeploymentOption", GoMethod: "ResetDeploymentOption"},
			_jsii_.MemberMethod{JsiiMethod: "resetDiskProvisioning", GoMethod: "ResetDiskProvisioning"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableHiddenProperties", GoMethod: "ResetEnableHiddenProperties"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpAllocationPolicy", GoMethod: "ResetIpAllocationPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpProtocol", GoMethod: "ResetIpProtocol"},
			_jsii_.MemberMethod{JsiiMethod: "resetLocalOvfPath", GoMethod: "ResetLocalOvfPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetOvfNetworkMap", GoMethod: "ResetOvfNetworkMap"},
			_jsii_.MemberMethod{JsiiMethod: "resetRemoteOvfUrl", GoMethod: "ResetRemoteOvfUrl"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineOvfDeployOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineVapp",
		reflect.TypeOf((*VirtualMachineVapp)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineVappOutputReference",
		reflect.TypeOf((*VirtualMachineVappOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "properties", GoGetter: "Properties"},
			_jsii_.MemberProperty{JsiiProperty: "propertiesInput", GoGetter: "PropertiesInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetProperties", GoMethod: "ResetProperties"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineVappOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineVtpm",
		reflect.TypeOf((*VirtualMachineVtpm)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.virtualMachine.VirtualMachineVtpmOutputReference",
		reflect.TypeOf((*VirtualMachineVtpmOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetVersion", GoMethod: "ResetVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "version", GoGetter: "Version"},
			_jsii_.MemberProperty{JsiiProperty: "versionInput", GoGetter: "VersionInput"},
		},
		func() interface{} {
			j := jsiiProxy_VirtualMachineVtpmOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
