// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package distributedvirtualswitch

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitch",
		reflect.TypeOf((*DistributedVirtualSwitch)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "activeUplinks", GoGetter: "ActiveUplinks"},
			_jsii_.MemberProperty{JsiiProperty: "activeUplinksInput", GoGetter: "ActiveUplinksInput"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "allowForgedTransmits", GoGetter: "AllowForgedTransmits"},
			_jsii_.MemberProperty{JsiiProperty: "allowForgedTransmitsInput", GoGetter: "AllowForgedTransmitsInput"},
			_jsii_.MemberProperty{JsiiProperty: "allowMacChanges", GoGetter: "AllowMacChanges"},
			_jsii_.MemberProperty{JsiiProperty: "allowMacChangesInput", GoGetter: "AllowMacChangesInput"},
			_jsii_.MemberProperty{JsiiProperty: "allowPromiscuous", GoGetter: "AllowPromiscuous"},
			_jsii_.MemberProperty{JsiiProperty: "allowPromiscuousInput", GoGetter: "AllowPromiscuousInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupnfcMaximumMbit", GoGetter: "BackupnfcMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "backupnfcMaximumMbitInput", GoGetter: "BackupnfcMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupnfcReservationMbit", GoGetter: "BackupnfcReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "backupnfcReservationMbitInput", GoGetter: "BackupnfcReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupnfcShareCount", GoGetter: "BackupnfcShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "backupnfcShareCountInput", GoGetter: "BackupnfcShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "backupnfcShareLevel", GoGetter: "BackupnfcShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "backupnfcShareLevelInput", GoGetter: "BackupnfcShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "blockAllPorts", GoGetter: "BlockAllPorts"},
			_jsii_.MemberProperty{JsiiProperty: "blockAllPortsInput", GoGetter: "BlockAllPortsInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "checkBeacon", GoGetter: "CheckBeacon"},
			_jsii_.MemberProperty{JsiiProperty: "checkBeaconInput", GoGetter: "CheckBeaconInput"},
			_jsii_.MemberProperty{JsiiProperty: "configVersion", GoGetter: "ConfigVersion"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "contactDetail", GoGetter: "ContactDetail"},
			_jsii_.MemberProperty{JsiiProperty: "contactDetailInput", GoGetter: "ContactDetailInput"},
			_jsii_.MemberProperty{JsiiProperty: "contactName", GoGetter: "ContactName"},
			_jsii_.MemberProperty{JsiiProperty: "contactNameInput", GoGetter: "ContactNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributes", GoGetter: "CustomAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "customAttributesInput", GoGetter: "CustomAttributesInput"},
			_jsii_.MemberProperty{JsiiProperty: "datacenterId", GoGetter: "DatacenterId"},
			_jsii_.MemberProperty{JsiiProperty: "datacenterIdInput", GoGetter: "DatacenterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "directpathGen2Allowed", GoGetter: "DirectpathGen2Allowed"},
			_jsii_.MemberProperty{JsiiProperty: "directpathGen2AllowedInput", GoGetter: "DirectpathGen2AllowedInput"},
			_jsii_.MemberProperty{JsiiProperty: "egressShapingAverageBandwidth", GoGetter: "EgressShapingAverageBandwidth"},
			_jsii_.MemberProperty{JsiiProperty: "egressShapingAverageBandwidthInput", GoGetter: "EgressShapingAverageBandwidthInput"},
			_jsii_.MemberProperty{JsiiProperty: "egressShapingBurstSize", GoGetter: "EgressShapingBurstSize"},
			_jsii_.MemberProperty{JsiiProperty: "egressShapingBurstSizeInput", GoGetter: "EgressShapingBurstSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "egressShapingEnabled", GoGetter: "EgressShapingEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "egressShapingEnabledInput", GoGetter: "EgressShapingEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "egressShapingPeakBandwidth", GoGetter: "EgressShapingPeakBandwidth"},
			_jsii_.MemberProperty{JsiiProperty: "egressShapingPeakBandwidthInput", GoGetter: "EgressShapingPeakBandwidthInput"},
			_jsii_.MemberProperty{JsiiProperty: "failback", GoGetter: "Failback"},
			_jsii_.MemberProperty{JsiiProperty: "failbackInput", GoGetter: "FailbackInput"},
			_jsii_.MemberProperty{JsiiProperty: "faulttoleranceMaximumMbit", GoGetter: "FaulttoleranceMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "faulttoleranceMaximumMbitInput", GoGetter: "FaulttoleranceMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "faulttoleranceReservationMbit", GoGetter: "FaulttoleranceReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "faulttoleranceReservationMbitInput", GoGetter: "FaulttoleranceReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "faulttoleranceShareCount", GoGetter: "FaulttoleranceShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "faulttoleranceShareCountInput", GoGetter: "FaulttoleranceShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "faulttoleranceShareLevel", GoGetter: "FaulttoleranceShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "faulttoleranceShareLevelInput", GoGetter: "FaulttoleranceShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "folder", GoGetter: "Folder"},
			_jsii_.MemberProperty{JsiiProperty: "folderInput", GoGetter: "FolderInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "hbrMaximumMbit", GoGetter: "HbrMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "hbrMaximumMbitInput", GoGetter: "HbrMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "hbrReservationMbit", GoGetter: "HbrReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "hbrReservationMbitInput", GoGetter: "HbrReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "hbrShareCount", GoGetter: "HbrShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "hbrShareCountInput", GoGetter: "HbrShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "hbrShareLevel", GoGetter: "HbrShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "hbrShareLevelInput", GoGetter: "HbrShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "host", GoGetter: "Host"},
			_jsii_.MemberProperty{JsiiProperty: "hostInput", GoGetter: "HostInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreOtherPvlanMappings", GoGetter: "IgnoreOtherPvlanMappings"},
			_jsii_.MemberProperty{JsiiProperty: "ignoreOtherPvlanMappingsInput", GoGetter: "IgnoreOtherPvlanMappingsInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberProperty{JsiiProperty: "ingressShapingAverageBandwidth", GoGetter: "IngressShapingAverageBandwidth"},
			_jsii_.MemberProperty{JsiiProperty: "ingressShapingAverageBandwidthInput", GoGetter: "IngressShapingAverageBandwidthInput"},
			_jsii_.MemberProperty{JsiiProperty: "ingressShapingBurstSize", GoGetter: "IngressShapingBurstSize"},
			_jsii_.MemberProperty{JsiiProperty: "ingressShapingBurstSizeInput", GoGetter: "IngressShapingBurstSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "ingressShapingEnabled", GoGetter: "IngressShapingEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "ingressShapingEnabledInput", GoGetter: "IngressShapingEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "ingressShapingPeakBandwidth", GoGetter: "IngressShapingPeakBandwidth"},
			_jsii_.MemberProperty{JsiiProperty: "ingressShapingPeakBandwidthInput", GoGetter: "IngressShapingPeakBandwidthInput"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4Address", GoGetter: "Ipv4Address"},
			_jsii_.MemberProperty{JsiiProperty: "ipv4AddressInput", GoGetter: "Ipv4AddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "iscsiMaximumMbit", GoGetter: "IscsiMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "iscsiMaximumMbitInput", GoGetter: "IscsiMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "iscsiReservationMbit", GoGetter: "IscsiReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "iscsiReservationMbitInput", GoGetter: "IscsiReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "iscsiShareCount", GoGetter: "IscsiShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "iscsiShareCountInput", GoGetter: "IscsiShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "iscsiShareLevel", GoGetter: "IscsiShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "iscsiShareLevelInput", GoGetter: "IscsiShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "lacpApiVersion", GoGetter: "LacpApiVersion"},
			_jsii_.MemberProperty{JsiiProperty: "lacpApiVersionInput", GoGetter: "LacpApiVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "lacpEnabled", GoGetter: "LacpEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "lacpEnabledInput", GoGetter: "LacpEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "lacpMode", GoGetter: "LacpMode"},
			_jsii_.MemberProperty{JsiiProperty: "lacpModeInput", GoGetter: "LacpModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "linkDiscoveryOperation", GoGetter: "LinkDiscoveryOperation"},
			_jsii_.MemberProperty{JsiiProperty: "linkDiscoveryOperationInput", GoGetter: "LinkDiscoveryOperationInput"},
			_jsii_.MemberProperty{JsiiProperty: "linkDiscoveryProtocol", GoGetter: "LinkDiscoveryProtocol"},
			_jsii_.MemberProperty{JsiiProperty: "linkDiscoveryProtocolInput", GoGetter: "LinkDiscoveryProtocolInput"},
			_jsii_.MemberProperty{JsiiProperty: "managementMaximumMbit", GoGetter: "ManagementMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "managementMaximumMbitInput", GoGetter: "ManagementMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "managementReservationMbit", GoGetter: "ManagementReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "managementReservationMbitInput", GoGetter: "ManagementReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "managementShareCount", GoGetter: "ManagementShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "managementShareCountInput", GoGetter: "ManagementShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "managementShareLevel", GoGetter: "ManagementShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "managementShareLevelInput", GoGetter: "ManagementShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "maxMtu", GoGetter: "MaxMtu"},
			_jsii_.MemberProperty{JsiiProperty: "maxMtuInput", GoGetter: "MaxMtuInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "multicastFilteringMode", GoGetter: "MulticastFilteringMode"},
			_jsii_.MemberProperty{JsiiProperty: "multicastFilteringModeInput", GoGetter: "MulticastFilteringModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "netflowActiveFlowTimeout", GoGetter: "NetflowActiveFlowTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "netflowActiveFlowTimeoutInput", GoGetter: "NetflowActiveFlowTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "netflowCollectorIpAddress", GoGetter: "NetflowCollectorIpAddress"},
			_jsii_.MemberProperty{JsiiProperty: "netflowCollectorIpAddressInput", GoGetter: "NetflowCollectorIpAddressInput"},
			_jsii_.MemberProperty{JsiiProperty: "netflowCollectorPort", GoGetter: "NetflowCollectorPort"},
			_jsii_.MemberProperty{JsiiProperty: "netflowCollectorPortInput", GoGetter: "NetflowCollectorPortInput"},
			_jsii_.MemberProperty{JsiiProperty: "netflowEnabled", GoGetter: "NetflowEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "netflowEnabledInput", GoGetter: "NetflowEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "netflowIdleFlowTimeout", GoGetter: "NetflowIdleFlowTimeout"},
			_jsii_.MemberProperty{JsiiProperty: "netflowIdleFlowTimeoutInput", GoGetter: "NetflowIdleFlowTimeoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "netflowInternalFlowsOnly", GoGetter: "NetflowInternalFlowsOnly"},
			_jsii_.MemberProperty{JsiiProperty: "netflowInternalFlowsOnlyInput", GoGetter: "NetflowInternalFlowsOnlyInput"},
			_jsii_.MemberProperty{JsiiProperty: "netflowObservationDomainId", GoGetter: "NetflowObservationDomainId"},
			_jsii_.MemberProperty{JsiiProperty: "netflowObservationDomainIdInput", GoGetter: "NetflowObservationDomainIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "netflowSamplingRate", GoGetter: "NetflowSamplingRate"},
			_jsii_.MemberProperty{JsiiProperty: "netflowSamplingRateInput", GoGetter: "NetflowSamplingRateInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkResourceControlEnabled", GoGetter: "NetworkResourceControlEnabled"},
			_jsii_.MemberProperty{JsiiProperty: "networkResourceControlEnabledInput", GoGetter: "NetworkResourceControlEnabledInput"},
			_jsii_.MemberProperty{JsiiProperty: "networkResourceControlVersion", GoGetter: "NetworkResourceControlVersion"},
			_jsii_.MemberProperty{JsiiProperty: "networkResourceControlVersionInput", GoGetter: "NetworkResourceControlVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "nfsMaximumMbit", GoGetter: "NfsMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "nfsMaximumMbitInput", GoGetter: "NfsMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "nfsReservationMbit", GoGetter: "NfsReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "nfsReservationMbitInput", GoGetter: "NfsReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "nfsShareCount", GoGetter: "NfsShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "nfsShareCountInput", GoGetter: "NfsShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "nfsShareLevel", GoGetter: "NfsShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "nfsShareLevelInput", GoGetter: "NfsShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "notifySwitches", GoGetter: "NotifySwitches"},
			_jsii_.MemberProperty{JsiiProperty: "notifySwitchesInput", GoGetter: "NotifySwitchesInput"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "portPrivateSecondaryVlanId", GoGetter: "PortPrivateSecondaryVlanId"},
			_jsii_.MemberProperty{JsiiProperty: "portPrivateSecondaryVlanIdInput", GoGetter: "PortPrivateSecondaryVlanIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putHost", GoMethod: "PutHost"},
			_jsii_.MemberMethod{JsiiMethod: "putPvlanMapping", GoMethod: "PutPvlanMapping"},
			_jsii_.MemberMethod{JsiiMethod: "putVlanRange", GoMethod: "PutVlanRange"},
			_jsii_.MemberProperty{JsiiProperty: "pvlanMapping", GoGetter: "PvlanMapping"},
			_jsii_.MemberProperty{JsiiProperty: "pvlanMappingInput", GoGetter: "PvlanMappingInput"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetActiveUplinks", GoMethod: "ResetActiveUplinks"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowForgedTransmits", GoMethod: "ResetAllowForgedTransmits"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowMacChanges", GoMethod: "ResetAllowMacChanges"},
			_jsii_.MemberMethod{JsiiMethod: "resetAllowPromiscuous", GoMethod: "ResetAllowPromiscuous"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupnfcMaximumMbit", GoMethod: "ResetBackupnfcMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupnfcReservationMbit", GoMethod: "ResetBackupnfcReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupnfcShareCount", GoMethod: "ResetBackupnfcShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetBackupnfcShareLevel", GoMethod: "ResetBackupnfcShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetBlockAllPorts", GoMethod: "ResetBlockAllPorts"},
			_jsii_.MemberMethod{JsiiMethod: "resetCheckBeacon", GoMethod: "ResetCheckBeacon"},
			_jsii_.MemberMethod{JsiiMethod: "resetContactDetail", GoMethod: "ResetContactDetail"},
			_jsii_.MemberMethod{JsiiMethod: "resetContactName", GoMethod: "ResetContactName"},
			_jsii_.MemberMethod{JsiiMethod: "resetCustomAttributes", GoMethod: "ResetCustomAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetDirectpathGen2Allowed", GoMethod: "ResetDirectpathGen2Allowed"},
			_jsii_.MemberMethod{JsiiMethod: "resetEgressShapingAverageBandwidth", GoMethod: "ResetEgressShapingAverageBandwidth"},
			_jsii_.MemberMethod{JsiiMethod: "resetEgressShapingBurstSize", GoMethod: "ResetEgressShapingBurstSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetEgressShapingEnabled", GoMethod: "ResetEgressShapingEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetEgressShapingPeakBandwidth", GoMethod: "ResetEgressShapingPeakBandwidth"},
			_jsii_.MemberMethod{JsiiMethod: "resetFailback", GoMethod: "ResetFailback"},
			_jsii_.MemberMethod{JsiiMethod: "resetFaulttoleranceMaximumMbit", GoMethod: "ResetFaulttoleranceMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetFaulttoleranceReservationMbit", GoMethod: "ResetFaulttoleranceReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetFaulttoleranceShareCount", GoMethod: "ResetFaulttoleranceShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetFaulttoleranceShareLevel", GoMethod: "ResetFaulttoleranceShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetFolder", GoMethod: "ResetFolder"},
			_jsii_.MemberMethod{JsiiMethod: "resetHbrMaximumMbit", GoMethod: "ResetHbrMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetHbrReservationMbit", GoMethod: "ResetHbrReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetHbrShareCount", GoMethod: "ResetHbrShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetHbrShareLevel", GoMethod: "ResetHbrShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetHost", GoMethod: "ResetHost"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetIgnoreOtherPvlanMappings", GoMethod: "ResetIgnoreOtherPvlanMappings"},
			_jsii_.MemberMethod{JsiiMethod: "resetIngressShapingAverageBandwidth", GoMethod: "ResetIngressShapingAverageBandwidth"},
			_jsii_.MemberMethod{JsiiMethod: "resetIngressShapingBurstSize", GoMethod: "ResetIngressShapingBurstSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetIngressShapingEnabled", GoMethod: "ResetIngressShapingEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetIngressShapingPeakBandwidth", GoMethod: "ResetIngressShapingPeakBandwidth"},
			_jsii_.MemberMethod{JsiiMethod: "resetIpv4Address", GoMethod: "ResetIpv4Address"},
			_jsii_.MemberMethod{JsiiMethod: "resetIscsiMaximumMbit", GoMethod: "ResetIscsiMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetIscsiReservationMbit", GoMethod: "ResetIscsiReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetIscsiShareCount", GoMethod: "ResetIscsiShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetIscsiShareLevel", GoMethod: "ResetIscsiShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetLacpApiVersion", GoMethod: "ResetLacpApiVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetLacpEnabled", GoMethod: "ResetLacpEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetLacpMode", GoMethod: "ResetLacpMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetLinkDiscoveryOperation", GoMethod: "ResetLinkDiscoveryOperation"},
			_jsii_.MemberMethod{JsiiMethod: "resetLinkDiscoveryProtocol", GoMethod: "ResetLinkDiscoveryProtocol"},
			_jsii_.MemberMethod{JsiiMethod: "resetManagementMaximumMbit", GoMethod: "ResetManagementMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetManagementReservationMbit", GoMethod: "ResetManagementReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetManagementShareCount", GoMethod: "ResetManagementShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetManagementShareLevel", GoMethod: "ResetManagementShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetMaxMtu", GoMethod: "ResetMaxMtu"},
			_jsii_.MemberMethod{JsiiMethod: "resetMulticastFilteringMode", GoMethod: "ResetMulticastFilteringMode"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetflowActiveFlowTimeout", GoMethod: "ResetNetflowActiveFlowTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetflowCollectorIpAddress", GoMethod: "ResetNetflowCollectorIpAddress"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetflowCollectorPort", GoMethod: "ResetNetflowCollectorPort"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetflowEnabled", GoMethod: "ResetNetflowEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetflowIdleFlowTimeout", GoMethod: "ResetNetflowIdleFlowTimeout"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetflowInternalFlowsOnly", GoMethod: "ResetNetflowInternalFlowsOnly"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetflowObservationDomainId", GoMethod: "ResetNetflowObservationDomainId"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetflowSamplingRate", GoMethod: "ResetNetflowSamplingRate"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkResourceControlEnabled", GoMethod: "ResetNetworkResourceControlEnabled"},
			_jsii_.MemberMethod{JsiiMethod: "resetNetworkResourceControlVersion", GoMethod: "ResetNetworkResourceControlVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetNfsMaximumMbit", GoMethod: "ResetNfsMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetNfsReservationMbit", GoMethod: "ResetNfsReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetNfsShareCount", GoMethod: "ResetNfsShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetNfsShareLevel", GoMethod: "ResetNfsShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetNotifySwitches", GoMethod: "ResetNotifySwitches"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPortPrivateSecondaryVlanId", GoMethod: "ResetPortPrivateSecondaryVlanId"},
			_jsii_.MemberMethod{JsiiMethod: "resetPvlanMapping", GoMethod: "ResetPvlanMapping"},
			_jsii_.MemberMethod{JsiiMethod: "resetStandbyUplinks", GoMethod: "ResetStandbyUplinks"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberMethod{JsiiMethod: "resetTeamingPolicy", GoMethod: "ResetTeamingPolicy"},
			_jsii_.MemberMethod{JsiiMethod: "resetTxUplink", GoMethod: "ResetTxUplink"},
			_jsii_.MemberMethod{JsiiMethod: "resetUplinks", GoMethod: "ResetUplinks"},
			_jsii_.MemberMethod{JsiiMethod: "resetVdpMaximumMbit", GoMethod: "ResetVdpMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetVdpReservationMbit", GoMethod: "ResetVdpReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetVdpShareCount", GoMethod: "ResetVdpShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetVdpShareLevel", GoMethod: "ResetVdpShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetVersion", GoMethod: "ResetVersion"},
			_jsii_.MemberMethod{JsiiMethod: "resetVirtualmachineMaximumMbit", GoMethod: "ResetVirtualmachineMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetVirtualmachineReservationMbit", GoMethod: "ResetVirtualmachineReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetVirtualmachineShareCount", GoMethod: "ResetVirtualmachineShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetVirtualmachineShareLevel", GoMethod: "ResetVirtualmachineShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetVlanId", GoMethod: "ResetVlanId"},
			_jsii_.MemberMethod{JsiiMethod: "resetVlanRange", GoMethod: "ResetVlanRange"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmotionMaximumMbit", GoMethod: "ResetVmotionMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmotionReservationMbit", GoMethod: "ResetVmotionReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmotionShareCount", GoMethod: "ResetVmotionShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetVmotionShareLevel", GoMethod: "ResetVmotionShareLevel"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanMaximumMbit", GoMethod: "ResetVsanMaximumMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanReservationMbit", GoMethod: "ResetVsanReservationMbit"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanShareCount", GoMethod: "ResetVsanShareCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetVsanShareLevel", GoMethod: "ResetVsanShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "standbyUplinks", GoGetter: "StandbyUplinks"},
			_jsii_.MemberProperty{JsiiProperty: "standbyUplinksInput", GoGetter: "StandbyUplinksInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "teamingPolicy", GoGetter: "TeamingPolicy"},
			_jsii_.MemberProperty{JsiiProperty: "teamingPolicyInput", GoGetter: "TeamingPolicyInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "txUplink", GoGetter: "TxUplink"},
			_jsii_.MemberProperty{JsiiProperty: "txUplinkInput", GoGetter: "TxUplinkInput"},
			_jsii_.MemberProperty{JsiiProperty: "uplinks", GoGetter: "Uplinks"},
			_jsii_.MemberProperty{JsiiProperty: "uplinksInput", GoGetter: "UplinksInput"},
			_jsii_.MemberProperty{JsiiProperty: "vdpMaximumMbit", GoGetter: "VdpMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "vdpMaximumMbitInput", GoGetter: "VdpMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "vdpReservationMbit", GoGetter: "VdpReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "vdpReservationMbitInput", GoGetter: "VdpReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "vdpShareCount", GoGetter: "VdpShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "vdpShareCountInput", GoGetter: "VdpShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "vdpShareLevel", GoGetter: "VdpShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "vdpShareLevelInput", GoGetter: "VdpShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "version", GoGetter: "Version"},
			_jsii_.MemberProperty{JsiiProperty: "versionInput", GoGetter: "VersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "virtualmachineMaximumMbit", GoGetter: "VirtualmachineMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "virtualmachineMaximumMbitInput", GoGetter: "VirtualmachineMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "virtualmachineReservationMbit", GoGetter: "VirtualmachineReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "virtualmachineReservationMbitInput", GoGetter: "VirtualmachineReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "virtualmachineShareCount", GoGetter: "VirtualmachineShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "virtualmachineShareCountInput", GoGetter: "VirtualmachineShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "virtualmachineShareLevel", GoGetter: "VirtualmachineShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "virtualmachineShareLevelInput", GoGetter: "VirtualmachineShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "vlanId", GoGetter: "VlanId"},
			_jsii_.MemberProperty{JsiiProperty: "vlanIdInput", GoGetter: "VlanIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "vlanRange", GoGetter: "VlanRange"},
			_jsii_.MemberProperty{JsiiProperty: "vlanRangeInput", GoGetter: "VlanRangeInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmotionMaximumMbit", GoGetter: "VmotionMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "vmotionMaximumMbitInput", GoGetter: "VmotionMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmotionReservationMbit", GoGetter: "VmotionReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "vmotionReservationMbitInput", GoGetter: "VmotionReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmotionShareCount", GoGetter: "VmotionShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "vmotionShareCountInput", GoGetter: "VmotionShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "vmotionShareLevel", GoGetter: "VmotionShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "vmotionShareLevelInput", GoGetter: "VmotionShareLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanMaximumMbit", GoGetter: "VsanMaximumMbit"},
			_jsii_.MemberProperty{JsiiProperty: "vsanMaximumMbitInput", GoGetter: "VsanMaximumMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanReservationMbit", GoGetter: "VsanReservationMbit"},
			_jsii_.MemberProperty{JsiiProperty: "vsanReservationMbitInput", GoGetter: "VsanReservationMbitInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanShareCount", GoGetter: "VsanShareCount"},
			_jsii_.MemberProperty{JsiiProperty: "vsanShareCountInput", GoGetter: "VsanShareCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "vsanShareLevel", GoGetter: "VsanShareLevel"},
			_jsii_.MemberProperty{JsiiProperty: "vsanShareLevelInput", GoGetter: "VsanShareLevelInput"},
		},
		func() interface{} {
			j := jsiiProxy_DistributedVirtualSwitch{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchConfig",
		reflect.TypeOf((*DistributedVirtualSwitchConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchHost",
		reflect.TypeOf((*DistributedVirtualSwitchHost)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchHostList",
		reflect.TypeOf((*DistributedVirtualSwitchHostList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_DistributedVirtualSwitchHostList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchHostOutputReference",
		reflect.TypeOf((*DistributedVirtualSwitchHostOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "devices", GoGetter: "Devices"},
			_jsii_.MemberProperty{JsiiProperty: "devicesInput", GoGetter: "DevicesInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "hostSystemId", GoGetter: "HostSystemId"},
			_jsii_.MemberProperty{JsiiProperty: "hostSystemIdInput", GoGetter: "HostSystemIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetDevices", GoMethod: "ResetDevices"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DistributedVirtualSwitchHostOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchPvlanMapping",
		reflect.TypeOf((*DistributedVirtualSwitchPvlanMapping)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchPvlanMappingList",
		reflect.TypeOf((*DistributedVirtualSwitchPvlanMappingList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_DistributedVirtualSwitchPvlanMappingList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchPvlanMappingOutputReference",
		reflect.TypeOf((*DistributedVirtualSwitchPvlanMappingOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "primaryVlanId", GoGetter: "PrimaryVlanId"},
			_jsii_.MemberProperty{JsiiProperty: "primaryVlanIdInput", GoGetter: "PrimaryVlanIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "pvlanType", GoGetter: "PvlanType"},
			_jsii_.MemberProperty{JsiiProperty: "pvlanTypeInput", GoGetter: "PvlanTypeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "secondaryVlanId", GoGetter: "SecondaryVlanId"},
			_jsii_.MemberProperty{JsiiProperty: "secondaryVlanIdInput", GoGetter: "SecondaryVlanIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DistributedVirtualSwitchPvlanMappingOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchVlanRange",
		reflect.TypeOf((*DistributedVirtualSwitchVlanRange)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchVlanRangeList",
		reflect.TypeOf((*DistributedVirtualSwitchVlanRangeList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_DistributedVirtualSwitchVlanRangeList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-vsphere.distributedVirtualSwitch.DistributedVirtualSwitchVlanRangeOutputReference",
		reflect.TypeOf((*DistributedVirtualSwitchVlanRangeOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "maxVlan", GoGetter: "MaxVlan"},
			_jsii_.MemberProperty{JsiiProperty: "maxVlanInput", GoGetter: "MaxVlanInput"},
			_jsii_.MemberProperty{JsiiProperty: "minVlan", GoGetter: "MinVlan"},
			_jsii_.MemberProperty{JsiiProperty: "minVlanInput", GoGetter: "MinVlanInput"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_DistributedVirtualSwitchVlanRangeOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
